#!/bin/sh

CHECK=false
LINK=false
CLONE=false

. "$TEST_SHELL_PATH/dbops-major-version-upgrade/abstract-major-version-upgrade"

shell_unit_test() {
  shell_unit_test_dbops_major_version_upgrade
  check_dbops_result
}
