cp "$PGBOUNCER_CONFIG_UPDATED_FILE_PATH/${PGBOUNCER_CONFIG_FILE_PATH##*/}" \
  "${PGBOUNCER_CONFIG_FILE_PATH}.tmp"
mv "${PGBOUNCER_CONFIG_FILE_PATH}.tmp" "${PGBOUNCER_CONFIG_FILE_PATH}"

exec /usr/local/bin/pgbouncer "$PGBOUNCER_CONFIG_FILE_PATH"
