ARG BASE_IMAGE
FROM "$BASE_IMAGE"
  USER root:root
  WORKDIR '/app/'
  COPY 'target/stackgres-distributedlogs-controller-runner.jar' '/app/stackgres-distributedlogs-controller.jar'
  COPY 'target/lib/' '/app/lib/'
  COPY 'src/main/docker/stackgres-distributedlogs-controller.sh' '/app/stackgres-distributedlogs-controller.sh'
  RUN chown jboss:jboss '/app/' -R
  RUN chmod 775 '/home/jboss' -R
  RUN chmod 775 '/app' -R
  RUN chmod 775 '/app/stackgres-distributedlogs-controller.sh'

  USER jboss:jboss
  ENV HOME=/app
  CMD '/app/stackgres-distributedlogs-controller.sh'
  EXPOSE 8080
  EXPOSE 8443
  ENV LANG="C.UTF-8"
  ENV LC_ALL="C.UTF-8"

