ARG BASE_IMAGE
FROM "$BASE_IMAGE"
  USER root:root
  WORKDIR '/app/'
  COPY 'target/stackgres-distributedlogs-controller-runner' '/app/stackgres-distributedlogs-controller'
  COPY 'src/main/docker/stackgres-distributedlogs-controller.native.sh' '/app/stackgres-distributedlogs-controller.sh'
  RUN chmod 775 '/app' -R
  RUN chmod 775 '/app/stackgres-distributedlogs-controller.sh'

  RUN echo 'jboss:x:1000:' >> /etc/group && \
    echo 'jboss:!::' >> /etc/gshadow && \
    echo 'jboss:x:1000:1000::/app:/bin/bash' >> /etc/passwd && \
    echo 'jboss:!!:18655:0:99999:7:::' >> /etc/shadow && \
    echo 'jboss:100000:65536' >> /etc/subgid
  USER jboss:jboss
  ENV HOME=/app
  CMD '/app/stackgres-distributedlogs-controller.sh'
  EXPOSE 8080
  EXPOSE 8443
  ENV LANG="C.UTF-8"
  ENV LC_ALL="C.UTF-8"

