ARG BASE_IMAGE
FROM "$BASE_IMAGE"
  USER root
  WORKDIR '/app/'
  COPY 'target/stackgres-distributedlogs-controller-runner.jar' '/app/stackgres-distributedlogs-controller.jar'
  COPY 'target/lib/' '/app/lib/'
  COPY 'src/main/docker/stackgres-distributedlogs-controller.sh' '/app/stackgres-distributedlogs-controller.sh'
  RUN chown nobody:nobody '/app/' -R
  RUN chmod 775 '/app'
  RUN chmod 775 '/app/stackgres-distributedlogs-controller.sh'

  CMD '/app/stackgres-distributedlogs-controller.sh'
  EXPOSE 8080
  EXPOSE 8443
  USER nobody
  ENV LANG="C.UTF-8"
  ENV LC_ALL="C.UTF-8"

