{
 "title": "Archiving",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_up{pod=\"$pod\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "No. WALs files archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_archiver_archived_count{instance=~\"${instance}:9187\"}[5m])*300",
     "legendFormat": "# of WALs archived"
    }
   ]
  },
  {
   "title": "Number of failed attempts for archiving WAL files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_archiver_failed_count{instance=~\"${instance}:9187\"}[5m])*300",
     "legendFormat": "# Archive attemps"
    }
   ]
  },
  {
   "title": "Last archive age (Seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_stat_archiver_last_archive_age{instance=~\"${instance}:9187\"}"
    }
   ]
  }
 ]
}