{
 "title": "Connection Pooling",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_up{pod=\"$pod\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Active Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_show_pools_cl_active{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}}, User: {{user}}"
    }
   ]
  },
  {
   "title": "Server Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_show_pools_sv_idle{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}}, User: {{user}}"
    }
   ]
  },
  {
   "title": "Server Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_show_pools_sv_active{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}}, User: {{user}}"
    }
   ]
  },
  {
   "title": "Waiting Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_show_pools_cl_waiting{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}}, User: {{user}}"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_show_stats_avg_xact_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}}  - XACT"
    },
    {
     "expr": "pgbouncer_show_stats_avg_query_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}} - QUERY"
    },
    {
     "expr": "pgbouncer_show_stats_avg_wait_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}} - WAIT"
    }
   ]
  },
  {
   "title": "Average traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_show_stats_avg_recv{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}} - RECV"
    },
    {
     "expr": "pgbouncer_show_stats_avg_query_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
     "legendFormat": "Database: {{database}}  - SENT"
    }
   ]
  }
 ]
}