{
 "title": "CurrentActivity",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_up{pod=\"$pod\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Show if the node is leader or replica node",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_replication_is_replica{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_activity_count{state='active', instance=~\"${instance}:9187\"})"
    },
    {
     "expr": "pg_settings_max_connections{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_activity_count{instance=~\"${instance}:9187\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"})"
    },
    {
     "expr": "pg_settings_max_connections{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Idle in transaction connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_activity_count{instance=~\"${instance}:9187\", state=~\"idle in transaction|idle in transaction (aborted)\"})"
    }
   ]
  },
  {
   "title": "Inactive Replication Slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(count(pg_replication_slots_active{instance=~\"${instance}:9187\"}==0),\"replicationslots\",\"active\",\"slots\",\".*\")"
    }
   ]
  },
  {
   "title": "Last metrics scrape",
   "type": "stat",
   "description": "Show if the last metrics scrape finish successfully or not. ",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_error{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Current Long Running Tx",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_long_running_transactions_age_in_seconds{instance=~\"${instance}:9187\"})"
    }
   ]
  },
  {
   "title": "Queries waiting",
   "type": "stat",
   "description": "Queries waiting for other process to finish",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_current_waiting_query{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "stat",
   "description": "Number of queries blocked by other pids",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_blocked_queries{instance=~\"${instance}:9187\"})"
    }
   ]
  },
  {
   "title": "Active VACUUM queries",
   "type": "stat",
   "description": "shows the active running vacuum queries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_vacuum_queries{instance=~\"${instance}:9187\"})"
    }
   ]
  },
  {
   "title": "Active ANALYZE queries",
   "type": "stat",
   "description": "shows the active running vacuum analyze queries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_vacuum_analyze{instance=~\"${instance}:9187\"})"
    }
   ]
  },
  {
   "title": "Vacuum progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_progress_vacuum_heap_blks_total{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-BLKS-TOTAL"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_vacuum_heap_blks_scanned{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-BLKS-SCANNED"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_vacuum_heap_blks_vacuumed{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-BLKS-VACUUMED"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_vacuum_index_vacuum_count{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - INDEX-VACUUM-COUNT"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_vacuum_max_dead_tuples{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - MAX-DEAD-TUPLES"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_vacuum_num_dead_tuples{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - NUM-DEAD-TUPLES"
    }
   ]
  },
  {
   "title": "Vacuum Cluster progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_progress_cluster_heap_tuples_scanned{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-TUPLES-SCANNED"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_cluster_heap_tuples_written{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-TUBLES-WRITTEN"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_cluster_heap_blks_total{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-BLKS-TOTAL"
    },
    {
     "expr": "sum by (datname) (pg_stat_progress_cluster_heap_blks_scanned{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}} - HEAP-BLKS-SCANNED"
    },
    {
     "expr": "pg_stat_progress_cluster_index_rebuild_count{instance=~\"${instance}:9187\"}",
     "legendFormat": "Database: {{datname}} - INDEX-REBUILD-COUNT"
    }
   ]
  }
 ]
}