{
 "title": "Db Objects",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_up{pod=\"$pod\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 bigger tables",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, pg_total_relation_size_bytes{instance=~\"${instance}:9187\"}))",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "More Consulted Tables (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (relname, instance,datname,schemaname) (rate(pg_stat_user_tables_idx_scan{instance=~\"${instance}:9187\"}[5m])) + sum by (relname, instance,datname,schemaname) (rate(pg_stat_user_tables_seq_scan{instance=~\"${instance}:9187\"}[5m])))",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "Table with more inserts (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_user_tables_n_tup_ins{instance=~\"${instance}:9187\"}[5m]))",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "Tables with more UPDATE operations (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_user_tables_n_tup_upd{instance=~\"${instance}:9187\"}[5m]))",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "Tables with more DELETE operations (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_user_tables_n_tup_del{instance=~\"${instance}:9187\"}[5m]))",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "Index bloat Size (Top 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, pg_index_bloat_size{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}}, Schema: {{schema_name}}, Table: {{tblname}}, Index: {{idxname}}"
    }
   ]
  },
  {
   "title": "Index Size (Top 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, pg_index_real_size{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}}, Schema: {{schema_name}}, Table: {{tblname}}, Index: {{idxname}}"
    }
   ]
  },
  {
   "title": "Index Bloat Ratio (Top 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, pg_index_bloat_ratio{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}}, Schema: {{schema_name}}, Table: {{tblname}}, Index: {{idxname}}"
    }
   ]
  },
  {
   "title": "Dead tuples (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_user_tables_n_dead_tup{instance=~\"${instance}:9187\"}[5m])*300)",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "Table Bloat Ratio (top 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20, pg_table_bloat_bloat_ratio{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}}, Schema:{{schemaname}}, Table: {{tablename}}"
    }
   ]
  },
  {
   "title": "Table Bloat Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, pg_table_bloat_bloat_size{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{tablename}}"
    }
   ]
  },
  {
   "title": "Table pages Extra size (Top 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, pg_table_bloat_extra_size{instance=~\"${instance}:9187\"})",
     "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{tablename}}"
    }
   ]
  }
 ]
}