{
 "title": "Queries",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_up{pod=\"$pod\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Slow Queries Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_slow_queries{instance=~\"${instance}:9187\", datname!=\"\"}",
     "legendFormat": "Database: {{datname}}"
    }
   ]
  },
  {
   "title": "Sequential Scans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,rate(pg_stat_user_tables_seq_tup_read{instance=~\"${instance}:9187\"}[5m]))>0",
     "legendFormat": "Database: {{datname}}, Table: {{relname}}"
    }
   ]
  },
  {
   "title": "Long running transaction age(sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_long_running_transactions_age_in_seconds{instance=~\"${instance}:9187\"}",
     "legendFormat": "Database: {{datname}}"
    }
   ]
  },
  {
   "title": "Blocked Queries Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_blocked_queries{instance=~\"${instance}:9187\"}",
     "legendFormat": "Database: {{datname}}, Table: {{table}}"
    }
   ]
  },
  {
   "title": "Number of long running transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_long_running_transactions_transactions{instance=~\"${instance}:9187\"}",
     "legendFormat": "Database: {{datname}}"
    }
   ]
  },
  {
   "title": "Queries largest  time lock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_oldest_blocked_age_seconds{instance=~\"${instance}:9187\"}",
     "legendFormat": "Database: {{datname}}"
    }
   ]
  },
  {
   "title": "Queries that are stuck being idle in transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stuck_idle_in_transaction_queries{instance=~\"${instance}:9187\"}",
     "legendFormat": "Database: {{datname}}"
    }
   ]
  },
  {
   "title": "SQL statement activity",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(50,pg_statements_calls_total{instance=~\"${instance}:9187\"})",
     "legendFormat": "Calls"
    },
    {
     "expr": "topk(50,pg_statements_mean_exec_time{instance=~\"${instance}:9187\"})",
     "legendFormat": "Exec"
    },
    {
     "expr": "topk(50,pg_statements_rows_total{instance=~\"${instance}:9187\"})",
     "legendFormat": "Total rows"
    }
   ]
  }
 ]
}