{
 "title": "Replication",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_up{pod=\"$pod\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Active Replication Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(pg_replication_slots_stats_active{instance=~\"${instance}:9187\"}==1)"
    }
   ]
  },
  {
   "title": "Active Replica Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_replication_status_lag_size{instance=~\"${instance}:9187\", state=\"streaming\"} and on (instance)(pg_replication_is_replica == 0))"
    }
   ]
  },
  {
   "title": "Current LSN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_wal_position_bytes{instance=~\"${instance}:9187\"}"
    }
   ]
  },
  {
   "title": "Inactive Replication Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_replication_slots_stats_active{instance=~\"${instance}:9187\"}==0)"
    }
   ]
  },
  {
   "title": "Replication lag (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_replication_lag{cluster_name=\"$cluster_name\"} and on (instance)(pg_replication_is_replica == 1)",
     "legendFormat": "Replication lag in pod {{pod}}"
    }
   ]
  },
  {
   "title": "Replication lag size",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_replication_status_lag_size{cluster_name=\"$cluster_name\"} and on (instance)(pg_replication_is_replica == 0)",
     "legendFormat": "Replica: {{application_name}}"
    }
   ]
  }
 ]
}