#!/bin/sh

. "$SPEC_PATH/abstract/patroni"

e2e_test_extra_hash() {
  "$SHELL" "$PROJECT_PATH/stackgres-k8s/ci/build/build-functions.sh" path_hash \
    "$(realpath --relative-to "$PROJECT_PATH" "$SPEC_PATH/abstract/patroni")"
}

e2e_test_install() {
  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2"

  deploy_curl_pod "$CLUSTER_NAMESPACE"

  wait_pods_running "$CLUSTER_NAMESPACE" 3
  wait_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Checking that all 3 ports (5432, 7432, 7433) in the patroni pods are openned and listeing for queries" ports_check

  run_test "Checking that is possible to connect using services is working" service_check

  run_test "Checking that pgbouncer port is not open" check_no_pgbouncer

  run_test "Check that patroni healthcheck endpoints are accesible" patroni_ports_check

  run_test "Check that patroni management endpoints are not accesible" patroni_management_check

  run_test "Check that patroni is not accisible directly" patroni_direct_check
}

ports_check() {
  RESPONSE_5432="$(run_query -i 0 -p 5432)"
  RESPONSE_7432="$(run_query -i 0 -p "$POSTGRES_PORT")"
  RESPONSE_7433="$(run_query -i 0 -p "$POSTGRES_REPLICATION_PORT")"

  if [ "$RESPONSE_5432" = "1" ] \
    && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ]
  then
    RESPONSE_5432="$(run_query -i 1 -p 5432)"
    RESPONSE_7432="$(run_query -i 0 -p "$POSTGRES_PORT")"
    RESPONSE_7433="$(run_query -i 0 -p "$POSTGRES_REPLICATION_PORT")"

    if ! {
      [ "$RESPONSE_5432" = "1" ] \
        && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ]
    }
    then
      fail "Not all ports of the replica node are working"
    fi
  else 
    fail "Not all ports of the primary node are working"
  fi
}

service_check() {
  RESPONSE_PRIMARY="$(run_query -h "$CLUSTER_NAME" -i 1 -p 5432)"

  if [ "$RESPONSE_PRIMARY" = "1" ]
  then
    RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-replicas -i 0 -p 5432)"
    if [ "$RESPONSE_REPLICA" = "1" ]
    then
      success "Connections are possible using services"
    else
      fail "Cannot connect to replica db using a kubernetes service"
    fi
  else
    fail "Cannot connect to primary db using a kubernetes service"
  fi
}

check_no_pgbouncer() {
  if run_query -i 0 -p 6432 > /dev/null
  then
    fail "pgbouncer port on primary server is open"
  else
    if run_query -i 1 -p 6432 > /dev/null
    then
      fail "pgbouncer port on replica server is open"
    else
      success "pgbouncer connections are closed"
    fi
  fi
}
