####
# This Dockerfile is used in order to build a container that runs the StackGres ITs
#
# Build the image with:
#
# docker build -f src/test/docker/Dockerfile.it -t stackgres/it:7.0 .
#
###
FROM docker:19.03

RUN wget -q -O /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
RUN chmod a+x /bin/kubectl
RUN wget -q -O /bin/kind  https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64
RUN chmod a+x /bin/kind
RUN wget -q -O /bin/k3d https://github.com/rancher/k3d/releases/download/v1.5.1/k3d-linux-amd64
RUN chmod a+x /bin/k3d
RUN wget -q https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz -O -|tar xz --strip-components=1 -C /bin -f - linux-amd64/helm
RUN apk add coreutils gnupg jq curl bash zsh