####
# This Dockerfile is used in order to build a container that runs the StackGres ITs
#
# Build the image with:
#
# docker build -f src/test/docker/Dockerfile.it -t stackgres/it:latest .
#
###
FROM communitycloud/docker-client:1.11.0
RUN wget -q -L -O /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.10/bin/linux/amd64/kubectl
RUN chmod a+x /bin/kubectl
RUN wget -q -L -O /bin/kind  https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-$(uname)-amd64
RUN chmod a+x /bin/kind
RUN wget -q -L https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz -O -|tar xz --strip-components=1 -C /bin -f - linux-amd64/helm linux-amd64/tiller
