#!/bin/sh

. "$TEST_SHELL_PATH/dbops/abstract-dbops"

test_shell() {
  LOCK_SLEEP=0
  date +%s > "$TEST_TARGET_PATH/lock_timestamp"
  ! (test_dbops)
}

run_op() {
  sleep 300
}

mock kubectl kubectl_mock_overwrite

kubectl_mock_overwrite() {
  mokked
  case "$*" in
    ("get $CLUSTER_CRD_NAME "*)
    echo '
      LOCK_POD=test
      LOCK_TIMESTAMP='"$(cat "$TEST_TARGET_PATH/lock_timestamp")"'
      RESOURCE_VERSION=test
      '
    echo 0 > "$TEST_TARGET_PATH/lock_timestamp"
    ;;
    *)
    not_mokked
    ;;
  esac
}
