#!/bin/sh

. "$TEST_SHELL_PATH/dbops/abstract-dbops"

shell_unit_test() {
  EXCLUSIVE_OP=true
  LOCK_SLEEP=0
  date +%s > "$TEST_TARGET_PATH/lock_timestamp"
  ! (shell_unit_test_dbops)
  check_dbops_result
}

run_op() {
  sleep 300
}

mock kubectl kubectl_mock_overwrite

kubectl_mock_overwrite() {
  mokked
  case "$*" in
    ("get $CLUSTER_CRD_NAME "*)
    echo '
      LOCK_POD=test
      LOCK_TIMEOUT='"$(cat "$TEST_TARGET_PATH/lock_timestamp")"'
      RESOURCE_VERSION=test
      '
    echo 0 > "$TEST_TARGET_PATH/lock_timestamp"
    ;;
    *)
    not_mokked
    ;;
  esac
}
