{
 "title": "StackGres Dashboard",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions ( 5min rate )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_postgres_ingress_postgres_transactions_commit{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - COMMIT"
    },
    {
     "expr": "rate(envoy_postgres_ingress_postgres_transactions_rollback{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - ROLLBACK"
    }
   ]
  },
  {
   "title": "SQL statements ( 5min rate )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_postgres_ingress_postgres_statements_update{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - UPDATE"
    },
    {
     "expr": "rate(envoy_postgres_ingress_postgres_statements_insert{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - INSERT"
    },
    {
     "expr": "rate(envoy_postgres_ingress_postgres_statements_delete{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - DELETE"
    },
    {
     "expr": "rate(envoy_postgres_ingress_postgres_statements_select{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - SELECT"
    },
    {
     "expr": "rate(envoy_postgres_ingress_postgres_statements_other{instance=~\"${instance}:8001\"}[5m])",
     "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - OTHER"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_messages_backend{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - BACKEND"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_messages_frontend{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - FRONTEND"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_messages_unknown{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} -  UNKNOWN"
      }
     ]
    },
    {
     "title": "ERROR messages ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_fatal{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - FATAL"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_error{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - ERROR"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_unknown{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - UNKNOWN"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_panic{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - PANIC"
      }
     ]
    },
    {
     "title": "NOTICE ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_unknown{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - UNKNOWN"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_notice{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - NOTICE"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_warning{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - WARNING"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_info{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - INFO"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_log{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - LOG"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_debug{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - DEBUG"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful logins",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_sessions{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} "
      }
     ]
    },
    {
     "title": "Sessions Encryption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_sessions_encrypted{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - ENCRYPTED"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_sessions_unencrypted{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - UNENCRYPTED"
      }
     ]
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "pg_static{release=\"$release\", instance=~\"${instance}:9187\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "singlestat",
     "description": "start time of the process",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
     "format": "dateTimeFromNow",
     "valueName": "avg",
     "targets": [
      {
       "expr": "process_start_time_seconds{release=\"$release\", instance=~\"${instance}:9187\"} * 1000"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"${instance}:9187\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{release=\"$release\", datname=~\"$datname\", instance=~\"${instance}:9187\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"${instance}:9187\"})"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_connections{release=\"$release\", instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "graph",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=~\"${instance}:9187\"}[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{release=\"$release\", instance=~\"${instance}:9187\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=~\"${instance}:9187\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"${instance}:9187\", state=\"active\"} !=0",
       "legendFormat": "Database: {{datname}}, State: {{state}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "rate(pg_stat_database_xact_rollback{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"${instance}:9187\", mode=~\"$mode\"} != 0",
       "legendFormat": "Database: {{datname}}, Type:{{mode}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"${instance}:9187\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "Database: {{datname}}, State: {{state}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=~\"${instance}:9187\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=~\"${instance}:9187\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=~\"${instance}:9187\", datname=~\"$datname\"})",
       "legendFormat": "Database: {{ datname }}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_alloc{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_clean{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_conflicts{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "rate(pg_stat_database_deadlocks{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_temp_bytes{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_database_size{instance=~\"${instance}:9187\", datname!~\"template0|template1\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Top 10 bigger tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, pg_total_relation_size_bytes{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "More Consulted Tables (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (relname, instance,datname,schemaname) (rate(pg_stat_user_tables_idx_scan{instance=~\"${instance}:9187\"}[5m])) + sum by (relname, instance,datname,schemaname) (rate(pg_stat_user_tables_seq_scan{instance=~\"${instance}:9187\"}[5m])))",
       "legendFormat": "DB: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Table with more inserts (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_tup_ins{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Tables with more UPDATE operations (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_tup_upd{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Tables with more DELETE operations (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_tup_del{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Index bloat (MB) ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, pg_index_bloat_mb{instance=~\"${instance}:9187\"})",
       "legendFormat": "DB: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}, Index: {{indexrelname}}"
      }
     ]
    },
    {
     "title": "Index Percentage Bloat(Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, pg_index_bloat_pct{instance=~\"${instance}:9187\"})",
       "legendFormat": "DB: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}, Index: {{indexrelname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dead tuples (top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_dead_tup{instance=~\"${instance}:9187\"}[5m])*300)",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Table Bloat Estimated Rows (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_table_bloat_est_rows{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema:{{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Table Bloat Percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_table_bloat_pct_bloat{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Top 20 Bigger Tables Size in MB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_table_bloat_size_mb{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Replication Slots",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(pg_replication_slots_active{instance=~\"${instance}:9187\"}==1)"
      }
     ]
    },
    {
     "title": "Inactive Replication Slots",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(pg_replication_slots_active{instance=~\"${instance}:9187\"}==0)"
      }
     ]
    },
    {
     "title": "Replication lag (seconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_replication_lag{instance=~\"${instance}:9187\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Current LSN",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_wal_position_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "No. of pending WALs files to be archived",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_archiver_pending_wal_count{instance=~\"${instance}:9187\"}",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Queries Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_slow_queries{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Number of long running transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_long_running_transactions_transactions{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Long running transaction age(sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_long_running_transactions_age_in_seconds{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Queries largest  time lock",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_oldest_blocked_age_seconds{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Blocked Queries Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_blocked_queries{instance=~\"${instance}:9187\"}",
       "legendFormat": "Type: {{type}}, Database: {{datname}}, Schema: {{schemaname}}, RelType: {{reltype}}, Relation: {{relname}}"
      }
     ]
    },
    {
     "title": "Queries that are stuck being idle in transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stuck_idle_in_transaction_queries{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    }
   ]
  }
 ]
}