package io.stackgres.cli.commands.cluster;

import io.stackgres.cli.YamlParser;
import io.stackgres.cli.client.ClusterCreationUpdate;
import io.stackgres.cli.client.MatriarchClient;
import io.stackgres.cli.commands.InteractivePrompt;
import io.stackgres.cli.commands.StackGresSubCommand;
import io.stackgres.cli.commands.ProgressMessages;
import io.stackgres.postgres.Extension;
import io.stackgres.postgres.Flavor;
import io.stackgres.postgres.PostgresCluster;
import io.stackgres.postgres.VolumeMount;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Option;
import picocli.CommandLine.Spec;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.function.Consumer;

@Command(name = "create", description = "Creates and starts a PostgreSQL cluster", usageHelpWidth = 160)
public class CreateClusterCommand extends StackGresSubCommand {

    private final MatriarchClient client = new MatriarchClient();

    @Spec
    CommandSpec spec;

    @Option(names = {"-n", "--name"}, description = "The cluster name (default: default)")
    String name;

    @Option(names = {"-F", "--flavor"}, description = "The database flavor (postgres|ivorysql; default: postgres)")
    String flavor;

    @Option(names = {"-v", "--version"}, description = "The PostgreSQL version (default: latest)")
    String version;

    @Option(names = {"-p", "--port"}, description = "The port of the PostgreSQL cluster (default: 5432 or randomly chosen if in use).")
    Integer port;

    @Option(names = {"--ivorysql-port"}, description = "The port for IvorySQL's Oracle-compatible listener (default: 1521 or randomly chosen if in use). Only valid for flavor 'ivorysql'.", paramLabel = "<port>")
    Integer ivorySqlPort;

    @Option(names = {"--listen-address"}, description = "The listen address of the PostgreSQL cluster (default: 0.0.0.0)")
    String listenAddress;

    @Option(names = {"-u", "--username"}, description = "The name of the superuser (default: postgres)")
    String username;

    @Option(names = {"-P", "--password"}, description = "The password of the superuser (generated by default)")
    String password;

    @Option(names = {"-t", "--tag"}, description = "A tag (key/value pair) to add to the cluster", split = ",", paramLabel = "<key=value>")
    Map<String, String> tags = new HashMap<>();

    @Option(names = {"--node-selector"}, description = "Only create instance(s) on nodes matching the given tag(s)", split = ",", paramLabel = "<key=value>")
    Map<String, String> nodeSelector = new HashMap<>();

    @Option(names = {"-e", "--extension"}, description = "The PostgreSQL extension(s) (comma-separated extension names)", split = ",", paramLabel = "<extension>")
    List<String> extensionList = new ArrayList<>();

    @Option(names = "--node", description = "The StackGres node ID to create the PostgreSQL instance(s) on.", paramLabel = "<id>")
    UUID slonyId;

    @Option(names = {"-c", "--config"}, description = "The path of the PostgreSQL config files (default: <pgdata>)", paramLabel = "<file>")
    Path configDir;

    @Option(names = "--pgdata", description = "The host path to mount PGDATA into PostgreSQL (default: /var/lib/stackgres/clusters/<cluster-name>)", paramLabel = "<path>")
    Path dataDir;

    @Option(names = "--logs", description = "The directory in which PostgreSQL will create its log files (default: /var/log/stackgres/<cluster-name>)", paramLabel = "<path>")
    Path logsDir;

    @Option(names = "--wal", description = "The directory in which PostgreSQL will create its WAL files (default: <pgdata>/pg_wal)", paramLabel = "<path>")
    Path walDir;

    @Option(names = "--volume", description = "Bind mount a volume (i.e. file or directory) from your disk to the PostgreSQL environment (format: <host-path>:<pg-env-path>)", paramLabel = "<volume>")
    List<String> volumes = new ArrayList<>();

    @Option(names = {"-f", "--file"}, description = "A YAML file containing a PostgreSQL cluster definition (overrides other options)", paramLabel = "<file>")
    Path yamlFile;

    @Option(names = {"--ha", "--high-availability"}, description = "Creates the cluster as high available (HA) Postgres cluster (powered by Patroni)")
    boolean highAvailability;

    @Option(names = {"-I", "--instances"}, description = "The number of HA PostgreSQL instances to create (default: 3, implies --high-availability)")
    Integer instances;

    @Option(names = {"--no-tls"}, description = "Disables TLS encryption for PostgreSQL connections (TLS is enabled by default)")
    boolean noTls;

    @Option(names = {"-i", "--interactive"}, description = "Prompts for the cluster information interactively (no other parameters are required)")
    boolean interactive;

    @Override
    public void run() {
        PostgresCluster cluster;

        if (yamlFile != null) {
            try {
                String yaml = Files.readString(yamlFile);
                cluster = new YamlParser().parseYaml(yaml);
            } catch (IOException e) {
                throw new CommandLine.ParameterException(spec.commandLine(), "Could not read YAML contents of file " + yamlFile, e);
            }
        } else {
            Flavor parsedFlavor = Flavor.fromId(flavor);
            List<Extension> extensions = Extension.extractExtensions(extensionList);
            List<VolumeMount> volumeMounts = VolumeMount.parseMounts(volumes);

            if (highAvailability && instances == null)
                instances = 3;
            else if (instances != null && !highAvailability)
                highAvailability = true;

            if (highAvailability) {
                if (instances < 1 || instances > 100)
                    throw new IllegalArgumentException("The number of HA PostgreSQL instances must be between 1 and 100");
                cluster = PostgresCluster.clusterHASlonyInstance(name, parsedFlavor, version, instances, port, listenAddress, username, password, tags, extensions, slonyId, configDir, dataDir, logsDir, walDir, volumeMounts);
            } else
                cluster = PostgresCluster.clusterSingleSlonyInstance(name, parsedFlavor, version, port, listenAddress, username, password, tags, extensions, slonyId, configDir, dataDir, logsDir, walDir, volumeMounts);

            if (ivorySqlPort != null) {
                if (parsedFlavor != Flavor.IVORY_SQL)
                    throw new IllegalArgumentException("The --ivorysql-port option can only be set for IvorySQL clusters");
                cluster.getInstances().forEach(i -> i.setIvorySqlPort(ivorySqlPort));
            }
        }

        if (noTls)
            cluster.setNoTls(true);

        if (interactive)
            new InteractivePrompt(spec.commandLine()).populateCreate(cluster, client);

        ProgressMessages messages = new ProgressMessages("Creating PostgreSQL cluster", spec.commandLine());
        if (debug) client.setDebug(messages);
        final String[] clusterName = {""};
        final boolean[] pending = {false};

        try {
            Consumer<ClusterCreationUpdate> statusConsumer = update -> {
                switch (update.status()) {
                    case CREATED -> {
                        clusterName[0] = update.name();
                        messages.add("Cluster " + clusterName[0] + " created");
                        if (cluster.getPassword() == null)
                            messages.add("Superuser password: " + update.password());
                    }
                    case HEALTHY -> messages.add("Cluster " + clusterName[0] + " started successfully");
                    case PENDING -> {
                        pending[0] = true;
                        messages.add(io.stackgres.cli.Strings.warnAnsi("Cluster " + clusterName[0]
                                + " is pending — it will be provisioned once a slony-linux agent connects"));
                    }
                }
            };
            client.createCluster(cluster, nodeSelector, statusConsumer);
            if (pending[0])
                messages.warning();
            else
                messages.done();
        } catch (Exception e) {
            messages.failed();
            throw e;
        }

        if (messages.isSuccessfullyDone()) {
            outln("""
                    
                    List all StackGres clusters with the following command: stackgres cluster list""");
        }
    }

}