---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
##
## Base operator rules
##
- apiGroups:
    - ''
  resources:
    - namespaces
  verbs:
    - get
    - list
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  resourceNames:
    - sgconfigs.stackgres.io
    - sgclusters.stackgres.io
    - sginstanceprofiles.stackgres.io
    - sgpgconfigs.stackgres.io
    - sgpoolconfigs.stackgres.io
    - sgbackups.stackgres.io
    - sgbackupconfigs.stackgres.io
    - sgobjectstorages.stackgres.io
    - sgdbops.stackgres.io
    - sgdistributedlogs.stackgres.io
    - sgshardedclusters.stackgres.io
    - sgshardedbackups.stackgres.io
    - sgshardeddbops.stackgres.io
    - sgscripts.stackgres.io
    - sgstreams.stackgres.io
  verbs:
    - get
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  resourceNames:
    - prometheuses.monitoring.coreos.com
  verbs:
    - get
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
  verbs:
    - create
    - watch
    - list
    - get
    - update
    - patch
    - delete
- apiGroups:
    - ''
  resources:
    - users
    - groups
  verbs:
    - impersonate

- apiGroups:
  - operators.coreos.com
  resources:
  - operators
  verbs:
  - list
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restapi
rules:
##
## Base restapi rules
##
- apiGroups:
    - authorization.k8s.io
  resources:
    - subjectaccessreviews
  verbs:
    - create
- apiGroups:
    - ''
  resources:
    - users
    - groups
  verbs:
    - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webconsole-admin
rules:
##
## Base webconsole admin rules
##
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
    - clusterrolebindings
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  resourceNames:
    - sgconfigs.stackgres.io
    - sgclusters.stackgres.io
    - sginstanceprofiles.stackgres.io
    - sgpgconfigs.stackgres.io
    - sgpoolconfigs.stackgres.io
    - sgbackups.stackgres.io
    - sgbackupconfigs.stackgres.io
    - sgobjectstorages.stackgres.io
    - sgdbops.stackgres.io
    - sgdistributedlogs.stackgres.io
    - sgshardedclusters.stackgres.io
    - sgscripts.stackgres.io
    - sgstreams.stackgres.io
  verbs:
    - get
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
- apiGroups:
    - ''
    - storage.k8s.io
  resources:
    - namespaces
    - storageclasses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ''
    - batch
  resources:
    - pods/exec
    - configmaps
    - secrets
    - jobs
  verbs:
    - create
- apiGroups:
    - ''
  resources:
    - pods/exec
  verbs:
    - get
- apiGroups:
    - ''
    - batch
  resources:
    - configmaps
    - secrets
    - jobs
  verbs:
    - delete
- apiGroups:
    - ''
  resources:
    - configmaps
    - secrets
  verbs:
    - patch
    - update
- apiGroups:
    - ''
    - batch
    - storage.k8s.io
  resources:
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
    - events
    - jobs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - stackgres.io
  resources:
    - sgclusters
    - sgpgconfigs
    - sginstanceprofiles
    - sgpoolconfigs
    - sgbackupconfigs
    - sgbackups
    - sgdistributedlogs
    - sgdbops
    - sgobjectstorages
    - sgscripts
    - sgshardedclusters
    - sgshardedbackups
    - sgshardeddbops
    - sgstreams
  verbs:
    - create
    - watch
    - list
    - get
    - update
    - patch
    - delete
- apiGroups:
    - stackgres.io
  resources:
    - sgconfigs
  verbs:
    - watch
    - list
    - get
    - update
    - patch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
    - rolebindings
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webconsole-writer
rules:
##
## Base webconsole writer rules
##
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  resourceNames:
    - sgconfigs.stackgres.io
    - sgclusters.stackgres.io
    - sginstanceprofiles.stackgres.io
    - sgpgconfigs.stackgres.io
    - sgpoolconfigs.stackgres.io
    - sgbackups.stackgres.io
    - sgbackupconfigs.stackgres.io
    - sgobjectstorages.stackgres.io
    - sgdbops.stackgres.io
    - sgdistributedlogs.stackgres.io
    - sgshardedclusters.stackgres.io
    - sgscripts.stackgres.io
    - sgstreams.stackgres.io
  verbs:
    - get
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
- apiGroups:
    - ''
    - storage.k8s.io
  resources:
    - namespaces
    - storageclasses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ''
    - batch
  resources:
    - pods/exec
    - configmaps
    - secrets
    - jobs
  verbs:
    - create
- apiGroups:
    - ''
  resources:
    - pods/exec
  verbs:
    - get
- apiGroups:
    - ''
    - batch
  resources:
    - configmaps
    - secrets
    - jobs
  verbs:
    - delete
- apiGroups:
    - ''
  resources:
    - configmaps
    - secrets
  verbs:
    - patch
    - update
- apiGroups:
    - ''
    - batch
    - storage.k8s.io
  resources:
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
    - events
    - jobs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - stackgres.io
  resources:
    - sgclusters
    - sgpgconfigs
    - sginstanceprofiles
    - sgpoolconfigs
    - sgbackupconfigs
    - sgbackups
    - sgdistributedlogs
    - sgdbops
    - sgobjectstorages
    - sgscripts
    - sgshardedclusters
    - sgshardedbackups
    - sgshardeddbops
    - sgstreams
  verbs:
    - create
    - watch
    - list
    - get
    - update
    - patch
    - delete
- apiGroups:
    - stackgres.io
  resources:
    - sgconfigs
  verbs:
    - watch
    - list
    - get
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webconsole-reader
rules:
##
## Base webconsole reader rules
##
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  resourceNames:
    - sgconfigs.stackgres.io
    - sgclusters.stackgres.io
    - sginstanceprofiles.stackgres.io
    - sgpgconfigs.stackgres.io
    - sgpoolconfigs.stackgres.io
    - sgbackups.stackgres.io
    - sgbackupconfigs.stackgres.io
    - sgobjectstorages.stackgres.io
    - sgdbops.stackgres.io
    - sgdistributedlogs.stackgres.io
    - sgshardedclusters.stackgres.io
    - sgscripts.stackgres.io
    - sgstreams.stackgres.io
  verbs:
    - get
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
- apiGroups:
    - ''
    - storage.k8s.io
  resources:
    - namespaces
    - storageclasses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ''
    - batch
  resources:
    - pods/exec
  verbs:
    - create
- apiGroups:
    - ''
  resources:
    - pods/exec
  verbs:
    - get
- apiGroups:
    - ''
    - batch
    - storage.k8s.io
  resources:
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
    - events
    - jobs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - stackgres.io
  resources:
    - sgclusters
    - sgpgconfigs
    - sginstanceprofiles
    - sgpoolconfigs
    - sgbackupconfigs
    - sgbackups
    - sgdistributedlogs
    - sgdbops
    - sgobjectstorages
    - sgscripts
    - sgshardedclusters
    - sgshardedbackups
    - sgshardeddbops
    - sgstreams
  verbs:
    - watch
    - list
    - get
- apiGroups:
    - stackgres.io
  resources:
    - sgconfigs
  verbs:
    - watch
    - list
    - get

#+kubebuilder:scaffold:rules
