#!/bin/sh

. "$SPEC_PATH/runbooks/abstract/pgbench"

e2e_test_extra_hash() {
  pgbench_extra_hash
}

e2e_test_install() {
  install_metric_server
  install_keda
  install_vertical_pod_autoscaler \
    --set-string updater.extraArgs.in-recommendation-bounds-eviction-lifetime-threshold=2s

  kubectl create namespace "$CLUSTER_NAMESPACE"

  pgbench_create_cluster 2

  pgbench_init_cluster 3
}

e2e_test_uninstall() {
  k8s_async_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Benchmarking cluster with horizontal autoscaling" benchmark_cluster_horizontal_autoscaling
}

benchmark_cluster_horizontal_autoscaling() {
  pgbench_create_cluster 2 \
    --set-string 'cluster.autoscaling.mode=horizontal' \
    --set 'cluster.autoscaling.minInstances=2' \
    --set 'cluster.autoscaling.maxInstances=3' \
    --set 'cluster.autoscaling.horizontal.pollingInterval=2' \
    --set 'cluster.autoscaling.horizontal.cooldownPeriod=2' \
    --set-string 'cluster.autoscaling.horizontal.replicasConnectionsUsageTarget=0.05'

  pgbench_wait_service "$CLUSTER_NAME-replicas"

  pgbench_collect_disk_performance

  pgbench_start bench -h "$CLUSTER_NAME-replicas" -S

  if wait_until eval 'kubectl get pod -n "$CLUSTER_NAMESPACE" \
    -l "app=StackGresCluster,stackgres.io/cluster-name=$CLUSTER_NAME,role=replica" -o name \
    | wc -l | grep -qxF 2'
  then
    AUTOSCALE_START="$(date +%s)"
    echo "success KEDA can scale the cluster based on connections"
  else
    echo "FAIL: KEDA can not scale the cluster based on connections"
    pgbench_stop
    return 1
  fi

  pgbench_wait_completion

  pgbench_print_results
  echo
  echo "Autoscaling completed at $AUTOSCALE_START"
}
