#!/bin/sh

. "$SPEC_PATH/runbooks/abstract/pgbench"

e2e_test_extra_hash() {
  pgbench_extra_hash
}

e2e_test_install() {
  kubectl create namespace "$CLUSTER_NAMESPACE"

  pgbench_create_cluster "${E2E_PGBENCH_INSTANCES:-2}"

  pgbench_init_cluster "$(( ${E2E_PGBENCH_INSTANCES:-2} + 1 ))"
}

e2e_test_uninstall() {
  k8s_async_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Benchmarking cluster read-only" benchmark_cluster
}

benchmark_cluster() {
  pgbench_wait_service "$CLUSTER_NAME-replicas"

  pgbench_collect_disk_performance

  # The benchmark targets the replicas, that only accept read-only transactions
  pgbench_run_load_steps bench -h "$CLUSTER_NAME-replicas" -S

  pgbench_print_results
}
