#!/bin/sh

. "$SPEC_PATH/runbooks/abstract/pgbench"

e2e_test_extra_hash() {
  pgbench_extra_hash
}

e2e_test_install() {
  kubectl create namespace "$CLUSTER_NAMESPACE"

  pgbench_create_cluster "${E2E_PGBENCH_INSTANCES:-2}"

  pgbench_init_cluster "$(( ${E2E_PGBENCH_INSTANCES:-2} + 1 ))"
}

e2e_test_uninstall() {
  k8s_async_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Benchmarking cluster" benchmark_cluster
}

benchmark_cluster() {
  pgbench_wait_service "$CLUSTER_NAME"

  pgbench_collect_disk_performance

  # shellcheck disable=SC2046
  pgbench_run_load_steps bench $(pgbench_builtin_workload) -h "$CLUSTER_NAME"

  pgbench_print_results
}
