#!/bin/sh

. "$SPEC_PATH/runbooks/abstract/pgbench"

e2e_test_extra_hash() {
  pgbench_extra_hash
}

e2e_test_install() {
  kubectl create namespace "$CLUSTER_NAMESPACE"

  install_prometheus_operator

  # shellcheck disable=SC2046
  create_or_replace_sharded_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "$(( 1 + ${E2E_PGBENCH_CITUS_SHARDS:-2} + ${E2E_PGBENCH_CITUS_QUERY_ROUTERS:-0} ))" 1 0 \
    $(pgbench_cluster_options) \
    $(pgbench_disk_benchmark_options cluster.pods "$CLUSTER_NAME-coord-data") \
    $(pgbench_shards_disk_benchmark_options "$(( ${E2E_PGBENCH_CITUS_SHARDS:-2} + ${E2E_PGBENCH_CITUS_QUERY_ROUTERS:-0} ))") \
    --set cluster.configurations.observability.prometheusAutobind=true \
    --set-string 'configurations.postgresconfig.postgresql\.conf.citus\.max_shared_pool_size='"${E2E_PGBENCH_CITUS_MAX_SHARED_POOL_SIZE:-$E2E_PGBENCH_MAX_CONNECTIONS}" \
    --set-string 'configurations.postgresconfig.postgresql\.conf.citus\.max_adaptive_executor_pool_size='"${E2E_PGBENCH_MAX_ADAPTIVE_EXECUTOR_POOL_SIZE:-16}" \
    --set-string 'configurations.postgresconfig.postgresql\.conf.citus\.executor_slow_start_interval='"${E2E_PGBENCH_CITUS_EXECUTOR_SLOW_START_INTERVAL:-10ms}" \
    --set-string 'configurations.postgresconfig.postgresql\.conf.citus\.max_cached_conns_per_worker='"${E2E_PGBENCH_CITUS_MAX_CACHED_CONNS_PER_WORKER:-1}" \
    --set-string 'configurations.postgresconfig.postgresql\.conf.citus\.force_max_query_parallelization='"${E2E_PGBENCH_CITUS_FORCE_MAX_QUERY_PARALLELIZATION:-off}" \
    --set-string 'configurations.postgresconfig.postgresql\.conf.cron\.database_name=postgres' \
    --set-string 'configurations.postgresconfig.postgresql\.conf.cron\.host=/var/run/postgresql' \
    --set-string 'configurations.postgresconfig.postgresql\.conf.shared_preload_libraries=pg_cron' \
    --set-string 'cluster.postgres.extensions[0].name=pg_cron'

  kubectl patch sgshardedcluster -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" --type merge -p 'spec: { coordinator: { managedSql: { scripts: [ { sgScript: set-query-routers } ] } } }'

  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  namespace: "$CLUSTER_NAMESPACE"
  name: set-query-routers
spec:
  scripts:
  - retryOnError: true
    script: |
      CREATE EXTENSION IF NOT EXISTS pg_cron;
      DO \$setup\$BEGIN
        IF EXISTS (SELECT * FROM cron.job WHERE jobname = 'update-query-routers-flags') THEN
          PERFORM cron.alter_job(
            jobid,
            '30 seconds',
            \$sql\$
              DO \$\$BEGIN
                PERFORM citus_set_node_property(nodename, nodeport, 'shouldhaveshards', false)
                FROM pg_dist_node
                WHERE shouldhaveshards AND groupid IN (SELECT generate_series($((1 + ${E2E_PGBENCH_CITUS_SHARDS:-2})), $((1 + ${E2E_PGBENCH_CITUS_SHARDS:-2} + ${E2E_PGBENCH_CITUS_QUERY_ROUTERS:-0} - 1))));
              END\$\$
            \$sql\$,
            'citus')
          FROM cron.job WHERE jobname = 'update-query-routers-flags';
        ELSE
          PERFORM cron.schedule_in_database(
            'update-query-routers-flags',
            '30 seconds',
            \$sql\$
              DO \$\$BEGIN
                PERFORM citus_set_node_property(nodename, nodeport, 'shouldhaveshards', false)
                FROM pg_dist_node
                WHERE shouldhaveshards AND groupid IN (SELECT generate_series($((1 + ${E2E_PGBENCH_CITUS_SHARDS:-2})), $((1 + ${E2E_PGBENCH_CITUS_SHARDS:-2} + ${E2E_PGBENCH_CITUS_QUERY_ROUTERS:-0} - 1))));
              END\$\$
            \$sql\$,
            'citus');
        END IF;
      END\$setup\$;
EOF

  deploy_psql_pod "$CLUSTER_NAMESPACE"

  wait_pods_running "$CLUSTER_NAMESPACE" "$(( 2 + ${E2E_PGBENCH_CITUS_SHARDS:-2} + ${E2E_PGBENCH_CITUS_QUERY_ROUTERS:-0} ))"
  wait_sharded_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"

  pgbench_read_password

  kubectl exec -n "$CLUSTER_NAMESPACE" psql -q\
    -- env "PGPASSWORD=$PGPASSWORD" psql -d citus -q -h "$CLUSTER_NAME" -c "
        DROP TABLE IF EXISTS public.pgbench_branches;
        DROP TABLE IF EXISTS public.pgbench_tellers;
        DROP TABLE IF EXISTS public.pgbench_accounts;
        DROP TABLE IF EXISTS public.pgbench_history;

        CREATE TABLE public.pgbench_branches (
            bid integer NOT NULL,
            bbalance integer,
            filler character(88)
        )
        WITH (fillfactor='100');
        CREATE TABLE public.pgbench_tellers (
            bid integer,
            tid integer NOT NULL,
            tbalance integer,
            filler character(84)
        )
        WITH (fillfactor='100');
        CREATE TABLE public.pgbench_accounts (
            bid integer,
            aid integer NOT NULL,
            abalance integer,
            filler character(84)
        )
        WITH (fillfactor='100');
        CREATE TABLE public.pgbench_history (
            bid integer,
            tid integer,
            aid integer,
            delta integer,
            mtime timestamp without time zone,
            filler character(22)
        );

        ALTER TABLE ONLY public.pgbench_branches
            ADD CONSTRAINT pgbench_branches_pkey PRIMARY KEY (bid);
        ALTER TABLE ONLY public.pgbench_tellers
            ADD CONSTRAINT pgbench_tellers_pkey PRIMARY KEY (bid, tid);
        ALTER TABLE ONLY public.pgbench_accounts
            ADD CONSTRAINT pgbench_accounts_pkey PRIMARY KEY (bid, aid);
        ALTER TABLE ONLY public.pgbench_history
            ADD CONSTRAINT pgbench_history_pkey PRIMARY KEY (bid, tid, aid);

        SELECT create_distributed_table('pgbench_branches', 'bid');
        SELECT create_distributed_table('pgbench_tellers', 'bid', colocate_with => 'pgbench_branches');
        SELECT create_distributed_table('pgbench_accounts', 'bid', colocate_with => 'pgbench_branches');
        SELECT create_distributed_table('pgbench_history', 'bid', colocate_with => 'pgbench_branches');

        INSERT INTO pgbench_branches (bid, bbalance)
          SELECT i, 0 FROM generate_series(1, 7) AS i;
        INSERT INTO pgbench_tellers (tid, bid, tbalance)
          SELECT i, 1 + ((i - 1) / 10), 0 FROM generate_series(1, 7 * 10) AS i;
        INSERT INTO pgbench_accounts (aid, bid, abalance)
          SELECT i, 1 + ((i - 1) / 100000), 0 FROM generate_series(1, 7 * 100000) AS i;
    "
}

e2e_test_uninstall() {
  k8s_async_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Benchmarking cluster" benchmark_cluster
}

benchmark_cluster() {
  pgbench_wait_service "$CLUSTER_NAME"
  pgbench_wait_service "$CLUSTER_NAME-workers"

  kubectl exec -n "$CLUSTER_NAMESPACE" psql -q\
    -- bash -c "printf %s '
           \set bid random(1, 1 * :scale)
           \set tid (:bid - 1) * 10 + random(1, 100000)
           \set aid (:bid - 1) * 100000 + random(1, 100000)
           \set delta random(-5000, 5000)
           BEGIN;
           UPDATE pgbench_accounts SET abalance = abalance + :delta WHERE aid = :aid AND bid = :bid;
           SELECT abalance FROM pgbench_accounts WHERE aid = :aid AND bid = :bid;
           UPDATE pgbench_tellers SET tbalance = tbalance + :delta WHERE tid = :tid AND bid = :bid;
           UPDATE pgbench_branches SET bbalance = bbalance + :delta WHERE bid = :bid;
           INSERT INTO pgbench_history (tid, bid, aid, delta, mtime)
             VALUES (:tid, :bid, :aid, :delta, CURRENT_TIMESTAMP);
           END;
      ' > /tmp/script"
  # Read-only counterpart of the script above. It derives its keys the same way
  # so that it reads the very rows the read-write script writes, and filters on
  # the distribution column so that Citus routes it to a single shard.
  kubectl exec -n "$CLUSTER_NAMESPACE" psql -q\
    -- bash -c "printf %s '
           \set bid random(1, 1 * :scale)
           \set aid (:bid - 1) * 100000 + random(1, 100000)
           SELECT abalance FROM pgbench_accounts WHERE aid = :aid AND bid = :bid;
      ' > /tmp/script-read"
  if [ "$E2E_PGBENCH_CITUS_MODE" = aggregated_queries ]
  then
    kubectl exec -n "$CLUSTER_NAMESPACE" psql -q\
      -- bash -c "printf %s '
            BEGIN;
            SELECT max(abalance) FROM pgbench_accounts;
            END;
        ' > /tmp/script2"
  elif [ "$E2E_PGBENCH_CITUS_MODE" = copy ]
  then
    kubectl exec -n "$CLUSTER_NAMESPACE" psql -q\
      -- bash -c "printf %s '
            BEGIN;
            \set bid random(1, 1 * :scale - 100000)
            \set tid (:bid - 1) * 10 + random(1, 100000)
            \set aid (:bid - 1) * 100000 + random(1, 100000)
            \set delta random(-5000, 5000)
            COPY (SELECT bid, :tid, :aid, :delta FROM generate_series(:bid, :bid + 100000) AS bid ) TO pgbench_history;
            END;
        ' > /tmp/script2"
  fi

  pgbench_collect_disk_performance

  # shellcheck disable=SC2046
  pgbench_run_load_steps bench -d citus \
    $(pgbench_script_workload /tmp/script /tmp/script-read) \
    $([ "$E2E_PGBENCH_CITUS_MODE" != aggregated_queries ] || printf %s "--file=/tmp/script2@${E2E_PGBENCH_CITUS_AGGREGATED_QUERIES_WEIGHT:-10}") \
    -h "$CLUSTER_NAME"

  pgbench_print_results
}
