#!/bin/sh

wait_dbops_is_completed() {
  local DBOPS_NAME="$1"
  if wait_until eval 'kubectl get sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME" \
    --template "{{ range .status.conditions }}{{ if eq .status \"True\" }}{{ .type }}{{ end }}{{ end }}" \
    | grep -q "^Completed$"'
  then
    echo "SUCCESS. The dbops has completed"
  else
    echo "FAIL. The dbops has failed or did not completed"
    return 1
  fi
}

wait_sharded_dbops_is_completed() {
  local SHARDED_DBOPS_NAME="$1"
  if wait_until eval 'kubectl get sgshardeddbops -n "$CLUSTER_NAMESPACE" "$SHARDED_DBOPS_NAME" \
    --template "{{ range .status.conditions }}{{ if eq .status \"True\" }}{{ .type }}{{ end }}{{ end }}" \
    | grep -q "^Completed$"'
  then
    echo "SUCCESS. The sharded dbops has completed"
  else
    echo "FAIL. The sharded dbops has failed or did not completed"
    return 1
  fi
}
