#!/bin/sh

set -e

SHELL="$(readlink /proc/$$/exe)"
if [ "$(basename "$SHELL")" = busybox ]
then
  SHELL=sh
fi

IMAGE_TAG="${IMAGE_TAG:-development-jvm}"
IMAGE_NAME="stackgres/operator:$IMAGE_TAG"
DEFAULT_K8S_VERSION="1.12.10"
KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
SPEC_PATH="$(dirname "$0")/spec"
TARGET_PATH="${TARGET_PATH:-$(dirname "$0")/target}"
TARGET_PATH="$(realpath $TARGET_PATH)"
LOG_PATH="$TARGET_PATH"
TRAP_ENABLED="${TRAP_ENABLED:-false}"

E2E_ENV="${E2E_ENV:-kind}"
K8S_VERSION="${K8S_VERSION:-$DEFAULT_K8S_VERSION}"
E2E_TIMEOUT="${E2E_TIMEOUT:-180}"
E2E_SKIP_SETUP="${E2E_SKIP_SETUP:-false}"
E2E_OPERATOR_PULL_POLICY="${E2E_OPERATOR_PULL_POLICY:-Never}"
E2E_BUILD_OPERATOR="${E2E_BUILD_OPERATOR:-true}"
E2E_WAIT_OPERATOR="${E2E_WAIT_OPERATOR:-true}"
E2E_USE_INTERMIDIATE_PRIVATE_REPO="${E2E_USE_INTERMIDIATE_PRIVATE_REPO:-false}"

if [ -z "$STACKGRES_PATH" ]
then
  STACKGRES_PATH="$(dirname "$0")/.."
fi
OPERATOR_CHART_PATH="${OPERATOR_CHART_PATH:-"$STACKGRES_PATH/install/helm/stackgres-operator/"}"
CLUSTER_CHART_PATH="${CLUSTER_CHART_PATH:-"$STACKGRES_PATH/install/helm/stackgres-cluster/"}"

export SHELL IMAGE_TAG IMAGE_NAME DEFAULT_K8S_VERSION KUBECONFIG SPEC_PATH TARGET_PATH TRAP_ENABLED OPERATOR_CHART_PATH CLUSTER_CHART_PATH
export E2E_ENV K8S_VERSION E2E_TIMEOUT E2E_SKIP_SETUP E2E_OPERATOR_PULL_POLICY E2E_BUILD_OPERATOR E2E_WAIT_OPERATOR

if ! command -v local > /dev/null 2>&1
then
  >&2 echo "You are probably using an AT&T Korn Shell or any other shell that does not support local variables in POSIX functions."
  exit 1
fi

for util in $(find "$(dirname "$0")/utils" -type f)
do
  . "$util"
done

. "$(dirname "$0")/envs/$E2E_ENV"

trap_kill() {
  echo "$1" >> "$TRAP_FILE"
}

trap_callback() {
  if [ -s "$TRAP_FILE" ]
  then
    sleep 1 || true # Let the tails write to output remaining logs.
    kill $(cat "$TRAP_FILE") >/dev/null 2>&1 || true
  fi
}

if [ -z "$TRAP_FILE" ]
then
  mkdir -p "$TARGET_PATH"
  TRAP_FILE="$TARGET_PATH/trap-kill-$(shuf -i 0-65535 -n 1)"
  export TRAP_FILE
  trap 'trap_callback' EXIT
  trap 'exit $?' HUP INT QUIT PIPE TERM
fi

trap_kill_all() {
  local file
  for file in $(find "$TARGET_PATH" -name 'trap-kill-*')
  do
    kill $(cat "$file") >/dev/null 2>&1 || true
  done
}

setup_k8s() {
  mkdir -p "$TARGET_PATH/logs"

  if [ "$E2E_SKIP_SETUP" = true ]
  then
    return
  fi

  if [ "$K8S_REUSE" != true ]
  then
    reset_k8s
  else
    reuse_k8s
  fi

  if [ "$E2E_SKIP_HELM_SETUP" != true ]
  then
    setup_helm

    setup_default_limits 0.1 0.1 16Mi 16Mi
  fi

  if [ "$E2E_BUILD_OPERATOR" = true ] \
    && (
      [ "$E2E_REUSE_OPERATOR" != true ] \
      || ! helm list --all-namespaces | grep -q "^stackgres-operator\s"
    )
  then
    (
    cd "$STACKGRES_PATH/src"
    ./mvnw -q clean package -P build-image-jvm
    )
  fi

  if ! helm list --all-namespaces | grep -q "^stackgres-operator\s" \
    || ! kubectl get namespaces stackgres -o name \
      | grep -q "^namespace/stackgres$" \
    || (! kubectl get deployments.apps -n stackgres -o name \
      | grep -q "^deployment.apps/stackgres-operator$" \
      && [ "$E2E_USE_EXTERNAL_OPERATOR" != true ])\
    || [ "$E2E_REUSE_OPERATOR" != true ]
  then
    if [ "$E2E_FORCE_IMAGE_PULL" = "true" ]
    then
      docker pull $IMAGE_NAME
    fi

    if [ "$E2E_USE_INTERMIDIATE_PRIVATE_REPO" != true ] \
      && docker image inspect "$IMAGE_NAME" >/dev/null 2>&1
    then 
      load_operator_k8s
    fi

    helm_cleanup
    k8s_cleanup

    install_operator

    if [ "$E2E_DEBUG_OPERATOR" = true ]
    then
      wait_pods_running stackgres
      kubectl set env -n stackgres deployment/stackgres-operator \
        DEBUG_OPERATOR="$E2E_DEBUG_OPERATOR" DEBUG_OPERATOR_SUSPEND="$E2E_DEBUG_OPERATOR_SUSPEND"
      kubectl delete pod -n stackgres "$(kubectl get pod -n stackgres -o name|cut -d / -f 2|tail -n 1)"
    fi
  else
    helm_cleanup_but_operator
    k8s_cleanup_but_operator
  fi

  if [ "$E2E_WAIT_OPERATOR" = true ]
  then
    wait_pods_running stackgres
  fi
  wait_pods_running
}

if [ "$(basename "$0")" = "e2e" -a ! -z "$1" ]
then
  "$@"
fi
