#!/bin/sh

test_install() {
  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 1

  wait_pods_running "$CLUSTER_NAMESPACE" 2
}

test() {
  run_test "Trying to delete backupconfig with cluster running" delete_with_cluster

  run_test "Trying to delete backupconfig without cluster running" delete_whitout_cluster
}

delete_with_cluster() {
  if kubectl get -n "$CLUSTER_NAMESPACE" sgbackupconfigs.stackgres.io backupconf -o yaml \
    | kubectl delete -f - > "${LOG_PATH}/test1.log" 2>&1
  then
    echo "FAIL: It should not be able to delete sgspconfig"
    return 1
  else
    echo "SUCCESS: Good it has failed"
  fi

  if grep -q "Can't delete sgbackupconfigs.stackgres.io backupconf" "$LOG_PATH/test1.log"
  then
    echo "SUCCESS: Error message was the expected"
    return 0
  else
    ERROR="$(cat "$LOG_PATH/test1.log")"
    echo "FAIL: Error is not what it should be. ERROR ${ERROR}"
    return 1
  fi
}

delete_whitout_cluster() {
  kubectl get -n "$CLUSTER_NAMESPACE" sgclusters.stackgres.io "$CLUSTER_NAME" -o yaml | kubectl delete -f -

  wait_pods_terminated "$CLUSTER_NAMESPACE" 1

  if kubectl get -n "$CLUSTER_NAMESPACE" sgbackupconfigs.stackgres.io backupconf -o yaml \
    | kubectl delete -f - > "${LOG_PATH}/test2.log" 2>&1
  then
    echo "SUCCESS: Good. It has deleted the configuration"
    return 0
  else
    ERROR="$(cat "$LOG_PATH/test2.log")"
    echo "FAIL: It should be able to delete the posgresconf. ERROR ${ERROR}"
    return 1
  fi
}
