#!/bin/sh

e2e_test_install_pods() {
  echo 2
}

e2e_test() {
  run_test "Checking that all 4 ports (5432, 6432, 7432, 7433) in the patroni pods are openned and listening for queries" ports_check

  run_test "Checking that is possible to connect using services is working" service_check

  run_test "Check that patroni healthcheck endpoints are accesible" patroni_ports_check

  run_test "Check that patroni management endpoints are not accesible" patroni_management_check

  run_test "Check that patroni is not accisible directly" patroni_direct_check
}

ports_check() {

  RESPONSE_5432="$(run_query -i 0 -p 5432)"
  RESPONSE_6432="$(run_query -i 0 -p 6432)"
  RESPONSE_7432="$(run_query -i 0 -p 7432)"
  RESPONSE_7433="$(run_query -i 0 -p 7433)"

  if [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ]
  then

    RESPONSE_5432="$(run_query -i 1 -p 5432)"
    RESPONSE_6432="$(run_query -i 1 -p 6432)"
    RESPONSE_7432="$(run_query -i 1 -p 7432)"
    RESPONSE_7433="$(run_query -i 1 -p 7433)"

    if [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ]
    then
      return 0
    else 
      echo "FAIL: Not all 4 ports of the replica node are working"
      return 1
    fi

  else 
      echo "FAIL: Not all 4 ports of the primary node are working"
      return 1
  fi

}

service_check() {
  RESPONSE_PRIMARY="$(run_query -h "$CLUSTER_NAME"-primary -i 1 -p 5432)"

  if [ "$RESPONSE_PRIMARY" = "1" ]
  then

    RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-replicas -i 0 -p 5432)"
    if [ "$RESPONSE_REPLICA" = "1" ]
    then
      echo "SUCCESS: Connections are possible using services"
      return 0
    else
      echo "FAIL: Cannot connect to replica db using a kubernetes service"
      return 1
    fi

  else
    echo "FAIL: Cannot connect to primary db using a kubernetes service"
    return 1
  fi
}
