#!/bin/sh

. "$SPEC_PATH/abstract/dbops-restart"

e2e_test_install() {
  DBOPS_NAME="$(get_sgdbops_name restart)"

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 1

  wait_pods_running "$CLUSTER_NAMESPACE" 1
}

e2e_test() {
  run_test "Checking that cluster restart fail when added invalid pgconf parameter" check_restart_cluster_fail
}

check_restart_cluster_fail() {

  if kubectl patch sgpgconfig -n "$CLUSTER_NAMESPACE" postgresconf --type json \
      -p '[{"op":"replace","path":"/spec/postgresql.conf/shared_preload_libraries","value":"pg_stat_statements, auto_explain, invalid-lib"}]' \
      >/dev/null 2>&1
    then
      echo "SUCCESS. sgpgconfig has been updated."
    else
      echo "FAILED. sgpgconfig has not been updated."
      return 1
  fi

  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: restart
  restart:
    method: InPlace
EOF

  if kubectl wait --timeout "$((E2E_TIMEOUT * 2))s" -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --for condition=Failed
  then
    echo "SUCCESS. The restart operator has been failed."
  else
    echo "FAILED. The restart operator has an unexpected status."
    return 1
  fi

  if kubectl patch sgpgconfig -n "$CLUSTER_NAMESPACE" postgresconf --type json \
    -p '[{"op":"replace","path":"/spec/postgresql.conf/shared_preload_libraries","value":"pg_stat_statements, auto_explain"}]' \
    >/dev/null 2>&1
  then
    echo "SUCCESS. sgpgconfig has been updated."
  else
    echo "FAILED. sgpgconfig has not been updated."
    return 1
  fi

  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME" > /dev/null 2>&1

  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: restart
  restart:
    method: InPlace
EOF

  check_restart_ran_successfully  

}