#!/bin/sh

e2e_test_install() {
  DBOPS_NAME=pgbench

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 2

  wait_pods_running "$CLUSTER_NAMESPACE" 2
  wait_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Checking that pgbench is working" check_pgbench_is_working

  run_test "Checking that pgbench is working with 10 clients and threads" check_pgbench_many_is_working

  run_test "Checking that pgbench is working with prepared statements" check_pgbench_prepared_is_working

  run_test "Checking that pgbench is working for replicas" check_pgbench_replicas_is_working

  run_test "Checking that pgbench timeout works correctly" check_pgbench_timed_out
}

check_pgbench_is_working() {
  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: benchmark
  benchmark:
    type: pgbench
    pgbench:
      databaseSize: 64Mi
      duration: PT10S
EOF

  wait_until eval '[ "$(kubectl get sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME" \
    --template "{{ .status.opRetries }}")" = "0" ]'
  kubectl get sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME" -o yaml > "$LOG_PATH/sgdbops.yaml"
  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"
  kubectl create -f "$LOG_PATH/sgdbops.yaml"

  check_pgbench

  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"
}

check_pgbench_many_is_working() {
  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: benchmark
  benchmark:
    type: pgbench
    pgbench:
      databaseSize: 64Mi
      duration: PT10S
      concurrentClients: 10
      threads: 10
EOF

  check_pgbench

  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"
}

check_pgbench_prepared_is_working() {
  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: benchmark
  benchmark:
    type: pgbench
    pgbench:
      databaseSize: 64Mi
      duration: PT10S
      usePreparedStatements: true
EOF

  check_pgbench

  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"
}

check_pgbench_replicas_is_working() {
  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: benchmark
  benchmark:
    type: pgbench
    pgbench:
      databaseSize: 64Mi
      duration: PT10S
    connectionType: replicas-service
EOF

  check_pgbench

  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"
}

check_pgbench() {
  assert_dbops_running "$DBOPS_NAME" "$CLUSTER_NAMESPACE"

  assert_dbops_completion "$DBOPS_NAME" "$CLUSTER_NAMESPACE"

  if [ "$(kubectl get -n "$CLUSTER_NAMESPACE" job \
    -l "dbops-name=$DBOPS_NAME,db-ops=true" \
    -o name 2>/dev/null | wc -l)" = 1 ]
  then
    echo "SUCCESS. pgbench job was not removed after completion."
  else
    echo "FAILED. pgbench job was removed after completion."
    return 1
  fi

  if kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.scaleFactor }}' | grep '[0-9]\+\(\.[0-9]\+\)\?'
  then
    echo "SUCCESS. pgbench returned the scale factor."
  else
    echo "FAILED. pgbench did not returned the scale factor."
    return 1
  fi

  if kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.transactionsProcessed }}' | grep '[0-9]\+\(\.[0-9]\+\)\?'
  then
    echo "SUCCESS. pgbench returned the transactions processed."
  else
    echo "FAILED. pgbench did not returned the transactions processed."
    return 1
  fi

  if kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.latency.average.value }}' | grep '[0-9]\+\(\.[0-9]\+\)\?'
  then
    echo "SUCCESS. pgbench returned the average latency."
  else
    echo "FAILED. pgbench did not returned the average latency."
    return 1
  fi

  if [ "$(kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.latency.average.unit }}')" \
    = "ms" ]
  then
    echo "SUCCESS. pgbench returned the average latency unit"
  else
    echo "FAILED. pgbench did not returned the average latency unit."
    return 1
  fi

  if kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.latency.standardDeviation.value}}' | grep '[0-9]\+\(\.[0-9]\+\)\?'
  then
    echo "SUCCESS. pgbench returned the latency standard deviation."
  else
    echo "FAILED. pgbench did not returned the latency standard deviation."
    return 1
  fi

  if [ "$(kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.latency.standardDeviation.unit}}')" \
    = "ms" ]
  then
    echo "SUCCESS. pgbench returned the latency standard deviation unit."
  else
    echo "FAILED. pgbench did not returned the latency standard deviation unit."
    return 1
  fi

  if kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.transactionsPerSecond.includingConnectionsEstablishing.value }}' | grep '[0-9]\+\(\.[0-9]\+\)\?'
  then
    echo "SUCCESS. pgbench returned the tps including connections establishing."
  else
    echo "FAILED. pgbench did not returned the tps including connections establishing."
    return 1
  fi

  if [ "$(kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.transactionsPerSecond.includingConnectionsEstablishing.unit }}')" \
    = "tps" ]
  then
    echo "SUCCESS. pgbench returned the tps including connections establishing unit."
  else
    echo "FAILED. pgbench did not returned the tps including connections establishing unit."
    return 1
  fi

  if kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.transactionsPerSecond.excludingConnectionsEstablishing.value }}' | grep '[0-9]\+\(\.[0-9]\+\)\?'
  then
    echo "SUCCESS. pgbench returned the tps excluding connections establishing."
  else
    echo "FAILED. pgbench did not returned the tps excluding connections establishing."
    return 1
  fi

  if [ "$(kubectl get -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --template '{{ .status.benchmark.pgbench.transactionsPerSecond.excludingConnectionsEstablishing.unit }}')" \
    = "tps" ]
  then
    echo "SUCCESS. pgbench returned the tps excluding connections establishing unit."
  else
    echo "FAILED. pgbench did not returned the tps excluding connections establishing unit."
    return 1
  fi

  RESULT="$(run_query -i 0 -p 5432 -q "SELECT EXISTS(SELECT * FROM pg_database WHERE datname = 'pgbench')")"
  if [ "$RESULT" = "f" ]
  then
    echo "SUCCESS. pgbench database was dropped."
  else
    echo "FAILED. pgbench database was not dropped."
    return 1
  fi
}

check_pgbench_timed_out() {
  cat << EOF | kubectl create -f -
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: $DBOPS_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  sgCluster: $CLUSTER_NAME
  op: benchmark
  timeout: PT1S
  benchmark:
    type: pgbench
    pgbench:
      databaseSize: 64Mi
      duration: PT10S
EOF

  if kubectl wait --timeout "${E2E_TIMEOUT}s" -n "$CLUSTER_NAMESPACE" sgdbops "$DBOPS_NAME" \
    --for condition=Failed
  then
    echo "SUCCESS. pgbench failed."
  else
    echo "FAILED. pgbench did not fail."
    return 1
  fi

  if [ "$(kubectl get -n "$CLUSTER_NAMESPACE" job \
    -l "dbops-name=$DBOPS_NAME,db-ops=true" \
    -o name 2>/dev/null | wc -l)" = 1 ]
  then
    echo "SUCCESS. pgbench job was not removed after failure."
  else
    echo "FAILED. pgbench job was removed after failure."
    return 1
  fi

  kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"

  if wait_until eval '[ "$(kubectl get -n "$CLUSTER_NAMESPACE" job \
    -l "dbops-name=$DBOPS_NAME,db-ops=true" \
    -o name 2>/dev/null | wc -l)" = 0 ]'
  then
    echo "SUCCESS. pgbench job was removed after sgdbops was removed."
  else
    echo "FAILED. pgbench job was not removed after sgdbops was removed."
    return 1
  fi
}
