#!/bin/sh

e2e_test_install() {
  DISTRIBUTED_LOGS_NAME=distributedlogs

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "1" \
    --set distributedLogs.enabled=false \
    --set distributedLogs.create=false

  create_or_replace_cluster "$CLUSTER_NAME-for-distributedlogs" "$CLUSTER_NAMESPACE" "1" \
    --set cluster.create=false \
    --set configurations.create=false \
    --set instanceProfiles=null \
    --set distributedLogs.enabled=true \
    --set distributedLogs.create=true \
    --set-string cluster.distributedLogs.sgDistributedLogs="$DISTRIBUTED_LOGS_NAME" \
    --set-string distributedLogs.persistentVolume.size=128Mi

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "1" \
    --set distributedLogs.enabled=true \
    --set distributedLogs.create=false \
    --set-string cluster.distributedLogs.sgDistributedLogs="$CLUSTER_NAMESPACE.$DISTRIBUTED_LOGS_NAME"

  wait_until eval '[ "$(kubectl get sts -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"
      --template '{{ .spec.template.spec.containers | len }}')" -eq 6 ]

  kubectl delete pod -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME-0"

  deploy_psql_pod "$CLUSTER_NAMESPACE"

  deploy_curl_pod "$CLUSTER_NAMESPACE"

  wait_pods_running "$CLUSTER_NAMESPACE" "4"
}

e2e_test() {
  run_test "Checking that default annotations where created" default_annotations

  run_test "Checking that distributed logs attach to clusters" check_distributed_logs_attach_to_clusters

  run_test "Checking that distributed logs query endpoint works correctly"  check_distributed_logs_query_endpoint
}

default_annotations(){
  local DEFAULT_ANNOTATION=$(kubectl get sgdistributedlogs.stackgres.io -n $CLUSTER_NAMESPACE $DISTRIBUTED_LOGS_NAME -o json | jq '.metadata.annotations["stackgres.io/operatorVersion"]')

  if [ -z "$DEFAULT_ANNOTATION" ] || [ "$DEFAULT_ANNOTATION" = "null" ]
  then
    echo "Fail. Default annotations not created"
    return 1
  else
    echo "Success. Defaults annotations created"
  fi
}

check_distributed_logs_attach_to_clusters() {
  create_or_replace_cluster "$CLUSTER_NAME-copy" "$CLUSTER_NAMESPACE" "1" \
    --set distributedLogs.enabled=true \
    --set distributedLogs.create=false \
    --set instanceProfiles=null \
    --set configurations.create=false \
    --set-string cluster.distributedLogs.sgDistributedLogs="$CLUSTER_NAMESPACE.$DISTRIBUTED_LOGS_NAME"

  wait_pods_running "$CLUSTER_NAMESPACE" "5"
  wait_services_available "$CLUSTER_NAMESPACE" "1" "$CLUSTER_NAME-primary"

  local TEXT
  local RESPONSE

  for TEXT in distributed-logs-worked distributed-logs-works distributed-logs-still-works
  do
    RESPONSE="$(run_query -c "$CLUSTER_NAME" -x psql -k postgres \
      -h "$CLUSTER_NAME"-primary -p 5432 -q "\"SELECT '$TEXT'\"")"

    if [ "$RESPONSE" = "$TEXT" ]
    then
      echo "SUCCESS: Log entry created"
    else
      echo "FAIL: Cannot create log entry"
      return 1
    fi
  done

  wait_services_available "$CLUSTER_NAMESPACE" "1" "$CLUSTER_NAME-copy-primary"

  for TEXT in distributed-logs-copy-worked distributed-logs-copy-works distributed-logs-copy-still-works
  do
    RESPONSE="$(run_query -c "$CLUSTER_NAME-copy" -x psql -k postgres \
      -h "$CLUSTER_NAME-copy"-primary -p 5432 -q "\"SELECT '$TEXT'\"")"

    if [ "$RESPONSE" = "$TEXT" ]
    then
      echo "SUCCESS: Log entry created"
    else
      echo "FAIL: Cannot create log entry"
      return 1
    fi
  done

  wait_services_available "$CLUSTER_NAMESPACE" "1" "$DISTRIBUTED_LOGS_NAME-primary"

  for TEXT in distributed-logs-worked distributed-logs-works distributed-logs-still-works
  do
    if wait_until eval 'get_logs_count_with_text "$TEXT" | grep -q "^1$"'
    then
      echo "SUCCESS: Cluster log entry included in json response for cluster $CLUSTER_NAME"
    else
      echo "FAIL: Cluster log entry not included in json response for cluster $CLUSTER_NAME"
      return 1
    fi
  done

  for TEXT in distributed-logs-copy-worked distributed-logs-copy-works distributed-logs-copy-still-works
  do
    if wait_until eval 'get_logs_count_with_text "$TEXT" -copy | grep -q "^1$"'
    then
      echo "SUCCESS: Cluster log entry included in json response for cluster $CLUSTER_NAME-copy"
    else
      echo "FAIL: Cluster log entry not included in json response for cluster $CLUSTER_NAME-copy"
      return 1
    fi
  done

  for TEXT in distributed-logs-copy-worked distributed-logs-copy-works distributed-logs-copy-still-works
  do
    if get_logs_count_with_text "$TEXT" | grep -q "^0$"
    then
      echo "SUCCESS: Cluster log entry of cluster $CLUSTER_NAME-copy not included in json response for cluster $CLUSTER_NAME"
    else
      echo "FAIL: Cluster log entry of cluster $CLUSTER_NAME-copy included in json response for cluster $CLUSTER_NAME"
      return 1
    fi
  done

  for TEXT in distributed-logs-worked distributed-logs-works distributed-logs-still-works
  do
    if get_logs_count_with_text "$TEXT" -copy | grep -q "^0$"
    then
      echo "SUCCESS: Cluster log entry of cluster $CLUSTER_NAME not included in json response for cluster $CLUSTER_NAME-copy"
    else
      echo "FAIL: Cluster log entry of cluster $CLUSTER_NAME included in json response for cluster $CLUSTER_NAME-copy"
      return 1
    fi
  done
}

check_distributed_logs_query_endpoint() {
  if get_logs_count_with_text distributed-logs-works | grep -q "^1$"
  then
    echo "SUCCESS: Cluster log entry included in json response"
  else
    echo "FAIL: Cluster log entry not included in json response"
    return 1
  fi

  if get_logs_count_with_text_after_log_with_text distributed-logs-works distributed-logs-still-works | grep -q "^1$"
  then
    echo "SUCCESS: Cluster log entry included in next json response with asc ordering"
  else
    echo "FAIL: Cluster log entry not included in next json response with asc ordering"
    return 1
  fi

  if get_logs_count_with_text_before_log_with_text distributed-logs-works distributed-logs-worked | grep -q "^1$"
  then
    echo "SUCCESS: Cluster log entry included in next json response with desc ordering"
  else
    echo "FAIL: Cluster log entry not included in next json response with desc ordering"
    return 1
  fi

  if get_logs_count_between_log_with_texts_desc distributed-logs-still-works distributed-logs-works distributed-logs-worked | grep -q "^2$"
  then
    echo "SUCCESS: Cluster log entries included in json response with from, to and desc ordering "
  else
    echo "FAIL: Cluster log entries not included in json response with from, to and desc ordering"
    return 1
  fi

  if get_logs_count_between_log_with_texts_asc distributed-logs-worked distributed-logs-works distributed-logs-still-works | grep -q "^2$"
  then
    echo "SUCCESS: Cluster log entries included in json response with from, to and asc ordering"
  else
    echo "FAIL: Cluster log entries not included in json response with from, to and asc ordering"
    return 1
  fi

  if get_postgres_logs_count_with_text distributed-logs-works | grep -q "^1$"
  then
    echo "SUCCESS: Cluster log entry included in json response"
  else
    echo "FAIL: Cluster log entry not included in json response"
    return 1
  fi

  if get_patroni_logs_count_with_text distributed-logs-works | grep -q "^0$"
  then
    echo "SUCCESS: Cluster log entry not included in json response"
  else
    echo "FAIL: Cluster log entry included in json response"
    return 1
  fi

  for field in \
    logType \
    podName \
    role \
    errorLevel \
    userName \
    databaseName
  do
    if get_logs_count_with_filter_of_log_with_text distributed-logs-works "$field" | grep -q "^1$"
    then
      echo "SUCCESS: Cluster log entry included in json response with filter on $field"
    else
      echo "FAIL: Cluster log entry not included in json response with filter on $field"
      return 1
    fi
  done
}

get_logs_count_with_text() {
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME$2?text=$1" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | length"
}

get_logs_count_with_text_after_log_with_text() {
  local LOG_TIME="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | .[0] | .logTime + \",\" + (.logTimeIndex|tostring)")"
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?from=$LOG_TIME&sort=asc" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select(.message != null and (.message | contains(\"$2\")))) | length"
}

get_logs_count_with_text_before_log_with_text() {
  local LOG_TIME="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | .[0] | .logTime + \",\" + (.logTimeIndex|tostring)")"
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?from=$LOG_TIME&sort=desc" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select(.message != null and (.message | contains(\"$2\")))) | length"
}

get_logs_count_between_log_with_texts_desc() {
  local START_LOG_TIME="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1&sort=desc" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | .[0] | .logTime + \",\" + (.logTimeIndex|tostring)")"
  local END_LOG_TIME="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$3&sort=desc" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$3\")))) | .[0] | .logTime + \",\" + (.logTimeIndex|tostring)")"
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?from=$START_LOG_TIME&to=$END_LOG_TIME&sort=desc" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select((.message != null and (.message | contains(\"$1\"))) or (.message != null and (.message | contains(\"$2\"))) or (.message != null and (.message | contains(\"$3\"))))) | length"
}

get_logs_count_between_log_with_texts_asc() {
  local START_LOG_TIME="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1&sort=asc" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | .[0] | .logTime + \",\" + (.logTimeIndex|tostring)")"
  local END_LOG_TIME="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$3&sort=asc" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$3\")))) | .[0] | .logTime + \",\" + (.logTimeIndex|tostring)")"
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?from=$START_LOG_TIME&to=$END_LOG_TIME&sort=asc" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select((.message != null and (.message | contains(\"$1\"))) or (.message != null and (.message | contains(\"$2\"))) or (.message != null and (.message | contains(\"$3\"))))) | length"
}

get_postgres_logs_count_with_text() {
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1&logType=pg" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | length"
}

get_patroni_logs_count_with_text() {
  local FILTER="{\"logType\":\"pa\"}"
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1&logType=pa" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | length"
}

get_logs_count_with_filter_of_log_with_text() {
  local FILTER="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1" \
    -n "$CLUSTER_NAMESPACE" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")))) | .[0] | .$2 | select(. == null) = \"\"")"
  local RESULT="$(run_curl \
    -r "stackgres/sgcluster/logs/$CLUSTER_NAMESPACE/$CLUSTER_NAME?text=$1&$2=$(uriencode "$FILTER")" \
    -n "$CLUSTER_NAMESPACE")"
  echo_raw "$RESULT" \
    | jq -r "map(select(.message != null and (.message | contains(\"$1\")) and (.$2 | select(. == null) = \"\" | tostring) == \"$FILTER\")) | length"
}

