#!/bin/sh

e2e_test_install() {
  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "4"

  wait_pods_running "$CLUSTER_NAMESPACE" "1"
}

e2e_test() {
  run_test "Check anti affinity is blocking pod creation" test_anti_affinity_is_blocking_pod_creation
}

test_anti_affinity_is_blocking_pod_creation() {
  local OLD_E2E_TIMEOUT="$E2E_TIMEOUT"
  E2E_TIMEOUT="$((E2E_TIMEOUT * 4))"

  if wait_until is_anti_affinity_blocking_pod_creation
  then
    echo "Cluster anti affinity is blocking pod creation"
  else
    echo "Cluster anti affinity isn't blocking pod creation"
    return 1
  fi

  E2E_TIMEOUT="$OLD_E2E_TIMEOUT"
}

is_anti_affinity_blocking_pod_creation() {
  kubectl get events -n "$CLUSTER_NAMESPACE" \
    --template '{{ range .items }}{{ .reason }}/{{ .involvedObject.kind }}/{{ .involvedObject.name }}/{{ .message }}{{ printf "\n" }}{{ end }}' \
    | grep "^FailedScheduling/Pod/$CLUSTER_NAME-[1-9]\+/" \
    | grep -F -q "node(s) didn't match pod affinity/anti-affinity"
}