#!/bin/sh

e2e_test() {
  run_test "Trying to delete sgpoolconfigs with cluster running" delete_with_cluster

  run_test "Trying to delete sgpoolconfigs without a cluster running" delete_whitout_cluster
}

delete_with_cluster() {
  if ERROR_MESSAGE=$( { kubectl delete -n "$CLUSTER_NAMESPACE" sgpoolconfigs.stackgres.io pgbouncerconf; } 2>&1 )
  then
    echo "ERROR: It should not be able to delete pgbouncerconf"
    return 1
  else
    echo "SUCCESS: Good it has failed"
  fi
  
  echo "$ERROR_MESSAGE" > "${LOG_PATH}/test1.log"

  if grep -q "Can't delete sgpoolconfigs.stackgres.io pgbouncerconf" "$LOG_PATH/test1.log"
  then
    echo "SUCCESS: Error message was the expected"
    return 0
  else
    ERROR="$(cat "$LOG_PATH/test1.log")"
    echo "FAIL: Error is not what it should be. ERROR: ${ERROR}"
    return 1
  fi
}

delete_whitout_cluster() {
  kubectl get -n "$CLUSTER_NAMESPACE" sgclusters.stackgres.io "$CLUSTER_NAME" -o yaml | kubectl delete -f - > /dev/null

  wait_pods_terminated "$CLUSTER_NAMESPACE"

  if kubectl delete -n "$CLUSTER_NAMESPACE" sgpoolconfigs.stackgres.io pgbouncerconf
  then
    echo "SUCCESS: Good. It has deleted the configuration"
    return 0
  else
    ERROR=$(kubectl delete -n "$CLUSTER_NAMESPACE" sgpoolconfigs.stackgres.io pgbouncerconf)
    echo "FAIL: It should be able to delete the pgbouncerconf. ERROR $ERROR"
    return 1
  fi
}
