#!/bin/sh

. "$SPEC_PATH/abstract/prometheus-integration"

prometheus_namespace() {
  echo "stackgres"
}

prometheus_service() {
  echo "stackgres-operator-prometh-prometheus"
}

e2e_exclusive_lock() {
  true
}

e2e_test_install() {
  delete_operator
  wait_pods_terminated "stackgres" 0
  install_operator \
    --disable-openapi-validation \
    --set grafana.autoEmbed=true \
    --set prometheus-operator.create=true \
    --set prometheus-operator.alertmanager.enabled=false \
    --set prometheus-operator.kubeStateMetrics.enabled=false \
    --set prometheus-operator.nodeExporter.enabled=false
  wait_pods_running "stackgres" 4

  kubectl create namespace "$CLUSTER_NAMESPACE"

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 1

  deploy_curl_pod "$CLUSTER_NAMESPACE"

  wait_pods_running "$CLUSTER_NAMESPACE" 2
}

e2e_test_uninstall() {
  delete_operator
  install_operator
  wait_pods_running "stackgres" 1

  helm_cleanup_chart "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"

  k8s_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Check that exporter service is created" check_exporter_service
  run_test "Check that exporter service monitor was created" check_exporter_service_monitor
  run_test "Check that envoy service is created" check_envoy_service
  run_test "Check that envoy service monitor was created" check_envoy_service_monitor
  run_test "Check that grafana is embedded" check_grafana_embedded
}
