#!/bin/sh

. "$SPEC_PATH/abstract/metrics"

e2e_test_install() {
  local PRIMARY_CLUSTER_NAME
  PRIMARY_CLUSTER_NAME="$(get_sgcluster_name "primary-$SPEC_NAME")"
  create_or_replace_cluster "$PRIMARY_CLUSTER_NAME" "$CLUSTER_NAMESPACE" "1"
  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2" \
    --set configurations.create=false \
    --set instanceProfiles=null \
    --set-string cluster.replicateFrom.instance.external.host="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.port="5433" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.superuser.username.name="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.superuser.username.key="PATRONI_SUPERUSER_USERNAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.superuser.password.name="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.superuser.password.key="PATRONI_SUPERUSER_PASSWORD" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.replication.username.name="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.replication.username.key="PATRONI_REPLICATION_USERNAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.replication.password.name="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.replication.password.key="PATRONI_REPLICATION_PASSWORD" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.authenticator.username.name="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.authenticator.username.key="PATRONI_authenticator_USERNAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.authenticator.password.name="$PRIMARY_CLUSTER_NAME" \
    --set-string cluster.replicateFrom.instance.external.secretKeyRefs.authenticator.password.key="PATRONI_authenticator_PASSWORD"

  deploy_curl_pod "$CLUSTER_NAMESPACE"

  wait_pods_running "$CLUSTER_NAMESPACE" "4"
  wait_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "Checking that standby is working" check_standby_is_working

  run_test "Checking that metrics are exported" check_metrics

  run_test "Checking that standby can be converted to primary" check_standby_can_be_converted_to_primary
}

check_standby_is_working() {
  wait_until check_connectivity -i 0

  local SYNCHRONOUS_STANDBY_NAMES
  SYNCHRONOUS_STANDBY_NAMES="$(kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME-0" -c postgres-util -- \
    psql -At -c 'SHOW synchronous_standby_names')"
  if echo "$SYNCHRONOUS_STANDBY_NAMES" | grep -q '^$'
  then
    echo "SUCCESS: async replication is set for leader"
  else
    echo "FAIL: async replication is not set for leader"
    return 1
  fi

  local RESULT EXIT_CODE
  try_function run_query -p 5432 -h "$CLUSTER_NAME" -i 1 -q "CREATE DATABASE test;"
  if "$RESULT"
  then
    echo "FAIL: It should not be possible to create a database in the leader node of the standby cluster"
    return 1
  else
    echo "SUCCESS: It is not possible to create a database in the leader node of the standby cluster" 
  fi

  wait_until check_connectivity -i 1
  try_function run_query -p 5432 -i 0 -h "$CLUSTER_NAME-replicas" -q "CREATE TABLE fibonacci(num integer);" -d test > "${LOG_PATH}/test1.log"
  if "$RESULT"
  then
    echo "FAIL: It's possible to create a table in the replica node"
    return 1
  else
    echo "SUCCESS: Good it is not possible to create a table in the replica node" 
  fi

  run_query -c "primary-$CLUSTER_NAME" -p 5432 -h "primary-$CLUSTER_NAME" -i 0 -q "CREATE TABLE fibonacci(num integer);" -d test
  run_query -c "primary-$CLUSTER_NAME" -p 5432 -h "primary-$CLUSTER_NAME" -i 0 -q "INSERT INTO fibonacci(num) VALUES (1);" -d test
  run_query -c "primary-$CLUSTER_NAME" -p 5432 -h "primary-$CLUSTER_NAME" -i 0 -q "INSERT INTO fibonacci(num) VALUES (2);" -d test
  run_query -c "primary-$CLUSTER_NAME" -p 5432 -h "primary-$CLUSTER_NAME" -i 0 -q "INSERT INTO fibonacci(num) VALUES (3);" -d test

  PRIMARY_RESPONSE="$(run_query -c "primary-$CLUSTER_NAME" -p 5432 -i 0 -h "primary-$CLUSTER_NAME" -q "SELECT num FROM fibonacci ORDER BY num;" -d "test")"

  if [ "$(echo "$PRIMARY_RESPONSE" | tr -d '\n')" = "123" ]
  then
    echo "SUCCESS: inserts on the primary where sucessful."
  else
    echo "FAIL: inserts on the primary where not sucessful."
    return 1
  fi

  try_function wait_until eval '
    STANDBY_RESPONSE="$(run_query -p 5432 -i 0 -h "$CLUSTER_NAME" -q "SELECT num FROM fibonacci ORDER BY num;" -d "test")"
    [ "$(echo "$PRIMARY_RESPONSE" | tr -d "\n")" = "$(echo "$STANDBY_RESPONSE" | tr -d "\n")" ]
    '
  if "$RESULT"
  then
    echo "SUCCESS: standby replication is working"
  else
    echo "FAIL: standby replication  is not working. The records don't match between primary and standby for the fibonacci table"
    return 1
  fi

  try_function wait_until eval '
    REPLICA_RESPONSE="$(run_query -p 5432 -i 0 -h "$CLUSTER_NAME-replicas" -q "SELECT num FROM fibonacci ORDER BY num;" -d "test")"
    [ "$(echo "$PRIMARY_RESPONSE" | tr -d "\n")" = "$(echo "$REPLICA_RESPONSE" | tr -d "\n")" ]
    '
  if "$RESULT"
  then
    echo "SUCCESS: replication is working"
  else
    echo "FAIL: replication is not working. The records don't match between primary and replica for the fibonacci table"
    return 1
  fi
}

check_standby_can_be_converted_to_primary() {
  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2" \
    --set configurations.create=false \
    --set instanceProfiles=null \
    --set cluster.replicateFrom=null

  local RESULT EXIT_CODE
  try_function wait_until run_query -p 5432 -h "$CLUSTER_NAME" -i 1 -q "CREATE DATABASE test;"
  if "$RESULT"
  then
    echo "SUCCESS: The leader node of the standby cluster was converted to a primary" 
  else
    echo "FAIL: The leader node of the standby cluster was not converted to a primary"
    return 1
  fi
}