#!/bin/sh
e2e_test_install() {
  kubectl create namespace "$CLUSTER_NAMESPACE"
  
  SERVICE="stackgres-restapi"
  local USERNAME="admin"
  local PASSWORD="$(kubectl get secrets -n "$OPERATOR_NAMESPACE" "$SERVICE" -o jsonpath="{.data.clearPassword}" | base64 -d)"
  CYPRESS_POD="cypress"
  
  cat << EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: $CYPRESS_POD
    namespace: $CLUSTER_NAMESPACE
  spec:
    containers:
    - name: $CYPRESS_POD
      image: cypress/included:4.8.0
      command: [ "sh", "-c", "while true; do sleep 300; done" ]
      imagePullPolicy: IfNotPresent
      env:
      - name: CYPRESS_host
        value: "https://$SERVICE.$OPERATOR_NAMESPACE/admin"
      - name: CYPRESS_username
        value: "$USERNAME"
      - name: CYPRESS_password
        value: "$PASSWORD"
      - name: CYPRESS_VIDEO
        value: "false" 
    restartPolicy: Always
    terminationGracePeriodSeconds: 0
EOF

  wait_pods_running "$CLUSTER_NAMESPACE" 1

  kubectl cp "$UI_TESTS_RESOURCES_PATH/cypress" "$CLUSTER_NAMESPACE/$CYPRESS_POD":/
  kubectl cp "$UI_TESTS_RESOURCES_PATH/cypress.json" "$CLUSTER_NAMESPACE/$CYPRESS_POD":/
   
}

e2e_test() {  
  run_test "Cypress chrome tests should pass" cypress_chrome_tests
  run_test "Cypress firefox tests should pass" cypress_firefox_tests
  run_test "Nginx must return the index page when a resource is not found" check_index_on_not_found_resource
}

cypress_chrome_tests(){
  kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- cypress run --headless  --browser chrome
}

cypress_firefox_tests(){
  kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- cypress run --headless  --browser firefox
}

check_index_on_not_found_resource(){
  random_resource=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)
  HTTP_STATUS=$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- curl -k "https://$SERVICE.$OPERATOR_NAMESPACE/admin/$random_resource" -X GET -LI -o /dev/null -w '%{http_code}')

  assert_string_equal "200" "$HTTP_STATUS"

  HTTP_RESPONSE=$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- curl -k "https://$SERVICE.$OPERATOR_NAMESPACE/admin/$random_resource -X GET -LI")

  if echo "$HTTP_RESPONSE" | grep -E "<meta.+index" > /dev/null
  then
    echo "SUCCESS. Returned index page on not found resource"
  else
    echo "FAIL. Index page not returned on not found resource"
    return 1
  fi
}