#!/bin/sh

prometheus_namespace() {
  echo "$CLUSTER_NAMESPACE-monitor"
}

prometheus_service() {
  echo "prometheus-kube-prometheus-prometheus"
}

e2e_exclusive_lock() {
  true
}

e2e_test_install() {
  k8s_cleanup_namespace "$OPERATOR_NAMESPACE"
  k8s_async_cleanup

  if [ "$E2E_ENV" = "minishift" ]
  then
    eval "$(minishift oc-env)"
    oc adm policy add-scc-to-user anyuid -n "$(prometheus_namespace)" -z prometheus-prometheus-oper-admission
    oc adm policy add-scc-to-user anyuid -n "$(prometheus_namespace)" -z prometheus-grafana
    oc adm policy add-scc-to-user anyuid -n "$(prometheus_namespace)" -z prometheus-prometheus-oper-operator
    oc adm policy add-scc-to-user anyuid -n "$(prometheus_namespace)" -z prometheus-prometheus-oper-prometheus
  fi

  install_prometheus

  wait_pods_running "$(prometheus_namespace)" 3

  kubectl create namespace "$OPERATOR_NAMESPACE"
  install_operator_only \
    --set adminui.service.exposeHTTP=true \
    --set grafana.autoEmbed=true \
    --set-string grafana.webHost="prometheus-grafana.$(prometheus_namespace)"

  wait_pods_terminated "$OPERATOR_NAMESPACE" 2

  kubectl create namespace "$CLUSTER_NAMESPACE"
  install_minio

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 2

  SERVICE="stackgres-restapi"
  local PASSWORD="$(kubectl get secrets -n "$OPERATOR_NAMESPACE" "$SERVICE" -o jsonpath="{.data.clearPassword}" | base64 -d)"
  CYPRESS_POD="cypress"
  
  cat << EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: $CYPRESS_POD
    namespace: $CLUSTER_NAMESPACE
  spec:
    containers:
    - name: $CYPRESS_POD
      image: cypress/included:4.8.0
      command: [ "sh", "-c", "while true; do sleep 300; done" ]
      imagePullPolicy: IfNotPresent
      env:
      - name: CYPRESS_host
        value: "https://$SERVICE.$OPERATOR_NAMESPACE/admin"
      - name: CYPRESS_username
        value: "admin"
      - name: CYPRESS_password
        value: "$PASSWORD"
      - name: CYPRESS_VIDEO
        value: "false" 
    restartPolicy: Always
    terminationGracePeriodSeconds: 0
EOF

  wait_pods_running "$CLUSTER_NAMESPACE" 5

  kubectl cp "$UI_TESTS_RESOURCES_PATH/cypress" "$CLUSTER_NAMESPACE/$CYPRESS_POD":/
  kubectl cp "$UI_TESTS_RESOURCES_PATH/cypress.json" "$CLUSTER_NAMESPACE/$CYPRESS_POD":/
}

install_prometheus(){
  kubectl create namespace "$(prometheus_namespace)" || true

  helm install prometheus prometheus-community/kube-prometheus-stack \
    --version 12.8.0 \
    --namespace "$(prometheus_namespace)" \
    --disable-openapi-validation \
    --set prometheusOperator.createCustomResource=false \
    --set alertmanager.enabled=false \
    --set kubeStateMetrics.enabled=false \
    --set nodeExporter.enabled=false \
    --set kubeDns.enabled=false \
    --set kubeProxy.enabled=false \
    --set kubeScheduler.enabled=false \
    --set coreDns.enabled=false \
    --set kubeControllerManager.enabled=false \
    --set kubeEtcd.enabled=false
}

e2e_test() {  
  run_test "Cypress chrome tests should pass" cypress_chrome_tests

  run_test "Cypress firefox tests should pass" cypress_firefox_tests

  run_test "Nginx must return the index page when a resource is not found" check_index_on_not_found_resource

  run_test "Nginx must work correctly on HTTP port when HTTP is exposed" check_http_port
}

cypress_chrome_tests(){
  kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- cypress run --headless  --browser chrome
}

cypress_firefox_tests(){
  kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- cypress run --headless  --browser firefox
}

check_index_on_not_found_resource(){
  random_resource=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)
  HTTP_STATUS=$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- curl -s -k "https://$SERVICE.$OPERATOR_NAMESPACE/admin/$random_resource" -X GET -LI -o /dev/null -w '%{http_code}' 2>/dev/null)

  assert_string_equal "200" "$HTTP_STATUS"

  HTTP_RESPONSE=$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- curl -s -k "https://$SERVICE.$OPERATOR_NAMESPACE/admin/$random_resource" -X GET -L 2>/dev/null)

  if echo "$HTTP_RESPONSE" | grep -E "<meta.+index" > /dev/null
  then
    echo "SUCCESS. Returned index page on not found resource"
  else
    echo "FAIL. Index page not returned on not found resource"
    return 1
  fi
}

check_http_port(){
  random_resource=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)
  HTTP_STATUS=$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CYPRESS_POD" -- curl -s "http://$SERVICE.$OPERATOR_NAMESPACE/admin" -X GET -LI -o /dev/null -w '%{http_code}' 2>/dev/null)

  if [ "$HTTP_STATUS" = "200" ]
  then
    echo "SUCCESS. HTTP port is working when exposed"
  else
    echo "FAIL. HTTP port is not working when exposed"
    return 1
  fi
}