#!/bin/sh

get_k8s_env_version() {
  true
}

reuse_k8s() {
  kubectl version
}

reset_k8s() {
  echo "Can not reset k8s cluster when using current configured k8s cluster"
  exit 1
}

delete_k8s() {
  echo "Can not delete k8s cluster when using current configured k8s cluster"
  exit 1
}

load_image_k8s() {
  echo "Can not load operator to k8s cluster when using current configured k8s cluster"
  exit 1
}
