#!/bin/sh

K8S_GKE_NAME="${K8S_GKE_NAME:-stackgres-e2e}"
K8S_VERSION="${K8S_VERSION:-1.13.12}"
if [ "$K8S_VERSION" = "$DEFAULT_K8S_VERSION" ]
then
  >&2 echo "Warning: using kubernetes version 1.13.11 since e2e default $DEFAULT_K8S_VERSION is not available for gke"
  K8S_VERSION=1.13.11
fi
K8S_GKE_VERSION="${K8S_GKE_VERSION:-gke.23}"
K8S_GKE_REGION="${K8S_GKE_REGION:-us-west1}"
K8S_GKE_NODE_LOCATIONS="${K8S_GKE_NODE_LOCATIONS:-us-west1-a,us-west1-b,us-west1-c}"
K8S_GKE_MACHINE_TYPE="${K8S_GKE_MACHINE_TYPE:-n1-standard-1}"
K8S_GKE_DISK_SIZE="${K8S_GKE_DISK_SIZE:-20}"
K8S_GKE_PROJECT="${K8S_GKE_PROJECT:-default}"
K8S_GKE_OPTS="$K8S_GKE_OPTS"
K8S_GKE_SERVICEACCOUNT="${K8S_GKE_SERVICEACCOUNT:-stackgres-e2e}"
export K8S_GKE_NAME K8S_VERSION K8S_GKE_VERSION K8S_GKE_REGION K8S_GKE_NODE_LOCATIONS K8S_GKE_MACHINE_TYPE K8S_GKE_DISK_SIZE K8S_GKE_PROJECT K8S_GKE_OPTS

reuse_k8s() {
  if ! gcloud -q beta container --project "$K8S_GKE_PROJECT" clusters describe "$K8S_GKE_NAME" --region "$K8S_GKE_REGION" 2>&1 \
    | grep -q "status: RUNNING"
  then
    echo "Can not reuse gke environment $K8S_GKE_NAME"
    reset_k8s
    return
  fi

  echo "Reusing gke environment $K8S_GKE_NAME"

  gcloud -q beta container --project "$K8S_GKE_PROJECT" clusters get-credentials "$K8S_GKE_NAME" --region "$K8S_GKE_REGION"
}

reset_k8s() {
  echo "Setting up gke environment $K8S_GKE_NAME..."

  delete_k8s
  gcloud -q beta container --project "$K8S_GKE_PROJECT" clusters create "$K8S_GKE_NAME" \
    --region "$K8S_GKE_REGION" \
    --node-locations "$K8S_GKE_NODE_LOCATIONS" \
    --machine-type "$K8S_GKE_MACHINE_TYPE" \
    --disk-size "$K8S_GKE_DISK_SIZE" \
    --num-nodes 3 \
    --cluster-version "$K8S_VERSION-$K8S_GKE_VERSION" \
    --no-enable-autoupgrade \
    $K8S_GKE_OPTS

  if [ ! -f "$TARGET_PATH/gke-service-account.json" ]
  then
    gcloud --project "$GKE_PROJECT" iam service-accounts create "$GKE_SERVICEACCOUNT" || true

    ACCOUNT_EMAIL=$GKE_SERVICEACCOUNT@$GKE_PROJECT.iam.gserviceaccount.com
    ACCOUNT_MEMBER="serviceAccount:$ACCOUNT_EMAIL"

    gcloud projects add-iam-policy-binding "$GKE_PROJECT" --member="$ACCOUNT_MEMBER" --role=roles/storage.admin || true

    gcloud iam service-accounts keys create "$TARGET_PATH/gke-service-account.json" --iam-account "$ACCOUNT_EMAIL"
    
  fi

  echo "...done"
}

delete_k8s() {
  echo "Deleting gke environment $K8S_GKE_NAME..."

  if gcloud -q beta container --project "$K8S_GKE_PROJECT" clusters describe "$K8S_GKE_NAME" --region "$K8S_GKE_REGION" 2>&1 \
    | grep -q "status: RUNNING"
  then
    gcloud -q beta container --project "$K8S_GKE_PROJECT" clusters delete "$K8S_GKE_NAME" --region "$K8S_GKE_REGION" || true
  fi
  gcloud -q compute disks list --project "$K8S_GKE_PROJECT" --filter "zone:($K8S_GKE_REGION)" \
    | tail -n+2 | sed 's/ \+/|/g' | cut -d '|' -f 1-2 \
    | grep '^gke-'"$K8S_GKE_NAME"'-[0-9a-f]\{4\}-pvc-[0-9a-f]\{8\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{12\}|' \
    | xargs -r -n 1 -I % sh $(! echo $- | grep -q x || echo "-x") -ec "gcloud -q compute disks delete --project '$K8S_GKE_PROJECT' --zone \"\$(echo '%' | cut -d '|' -f 2)\" \"\$(echo '%' | cut -d '|' -f 1)\""

  echo "...done"
}

load_operator_k8s() {
  echo "Loading operator image $IMAGE_NAME in gke environemnt $K8S_GKE_NAME..."

  docker tag "$IMAGE_NAME" "gcr.io/$K8S_GKE_PROJECT/$IMAGE_NAME"
  gcloud -q docker -- push "gcr.io/$K8S_GKE_PROJECT/$IMAGE_NAME"

  echo "...done"
}

operator_pull_policy() {
  echo IfNotPresent
}

excluded_mutatingwebhookconfigurations() {
  echo "pod-ready.config.common-webhooks.networking.gke.io"
}

excluded_customresourcedefinitions() {
  echo "backendconfigs.cloud.google.com"
  echo "managedcertificates.networking.gke.io"
  echo "scalingpolicies.scalingpolicy.kope.io"
  echo "updateinfos.nodemanagement.gke.io"
}
