{{- if .Values.repository.cache.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-docir-cache
  namespace: {{ .Release.Namespace }}
{{- if or .Values.serviceAccount.repoCredentials .Values.imagePullSecrets }}
imagePullSecrets:
{{- with .Values.serviceAccount.repoCredentials }}
{{- range . }}
- name: {{ . }}
{{- end }}
{{- end }}
{{- with .Values.imagePullSecrets }}
{{ . | toYaml }}
{{- end }}
{{- end }}
{{- end }}
