{
 "title": "StackGres Dashboard",
 "description": "This dashboard works with StackGres",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(up{namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(up{namespace=\"$namespace\", pod=\"$pod\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": "query_result(pg_up{pod=\"$pod\"})"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"${instance}:9187\", state=\"active\"} !=0",
       "legendFormat": "Database: {{datname}}, State: {{state}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"${instance}:9187\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "Database: {{datname}}, State: {{state}}"
      }
     ]
    },
    {
     "title": "Updated data (Rows)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"${instance}:9187\"}[5m]) != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Fetched data (Rows)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"${instance}:9187\"}[5m]) != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "Database: {{datname}} - COMMIT"
      },
      {
       "expr": "rate(pg_stat_database_xact_rollback{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "Database: {{datname}} - ROLLBACK"
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}, Type:{{mode}}"
      }
     ]
    },
    {
     "title": "Returned data (Rows)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"${instance}:9187\"}[5m]) != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Inserted data (Rows)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"${instance}:9187\"}[5m]) != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Deleted data (Rows)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"${instance}:9187\"}[5m]) != 0",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=~\"${instance}:9187\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=~\"${instance}:9187\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=~\"${instance}:9187\", datname=~\"$datname\"})",
       "legendFormat": "Database: {{ datname }}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_alloc{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_clean{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_conflicts{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "Database {{datname}} conflicts"
      },
      {
       "expr": "rate(pg_stat_database_deadlocks{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "Database {{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_temp_bytes{instance=~\"${instance}:9187\", datname=~\"$datname\"}[5m])",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Tables near to vacuum wraparound",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_vaccuum_wraparound_percent{datname=~\"$datname\", instance=~\"${instance}:9187\"} != 0",
       "legendFormat": "Database: {{datname}}, Table:{{full_table_name}}"
      }
     ]
    },
    {
     "title": "Checkpoint Duration Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{instance=~\"${instance}:9187\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    },
    {
     "title": "Checkpoint frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(pg_stat_bgwriter_checkpoints_timed{instance=~\"${instance}:9187\"}[5m])) by (instance), \"distinct\", \"Timed\", \"timed\", \".*\")*300 or label_replace(sum(rate(pg_stat_bgwriter_checkpoints_req{instance=~\"${instance}:9187\"}[5m])) by (instance), \"distinct\", \"Requested\", \"requested\", \".*\")*300",
       "legendFormat": "{{distinct}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pooling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pgbouncer_show_pools_cl_active{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}}, User: {{user}}"
      }
     ]
    },
    {
     "title": "Waiting Clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pgbouncer_show_pools_cl_waiting{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}}, User: {{user}}"
      }
     ]
    },
    {
     "title": "Server Active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pgbouncer_show_pools_sv_active{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}}, User: {{user}}"
      }
     ]
    },
    {
     "title": "Server Idle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pgbouncer_show_pools_sv_idle{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}}, User: {{user}}"
      }
     ]
    },
    {
     "title": "Average Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "pgbouncer_show_stats_avg_xact_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}}  - XACT"
      },
      {
       "expr": "pgbouncer_show_stats_avg_query_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}} - QUERY"
      },
      {
       "expr": "pgbouncer_show_stats_avg_wait_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}} - WAIT"
      }
     ]
    },
    {
     "title": "Average traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pgbouncer_show_stats_avg_recv{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}} - RECV"
      },
      {
       "expr": "pgbouncer_show_stats_avg_query_time{instance=~\"${instance}:9187\",database!~\"pgbouncer\"}",
       "legendFormat": "Database: {{database}}  - SENT"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_transactions_commit{pod=~\"${instance}:8001\"}[5m])",
       "legendFormat": "COMMIT"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_transactions_rollback{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "ROLLBACK"
      }
     ]
    },
    {
     "title": "SQL statements ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_statements_update{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "UPDATE"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_statements_insert{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "INSERT"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_statements_delete{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "DELETE"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_statements_select{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "SELECT"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_statements_other{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "OTHER"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_messages_backend{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "BACKEND"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_messages_frontend{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "FRONTEND"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_messages_unknown{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "UNKNOWN"
      }
     ]
    },
    {
     "title": "ERROR messages ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_fatal{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "FATAL"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_error{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "ERROR"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_unknown{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "UNKNOWN"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_errors_panic{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "PANIC"
      }
     ]
    },
    {
     "title": "NOTICE ( 5min rate )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_unknown{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "UNKNOWN"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_notice{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "NOTICE"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_warning{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "WARNING"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_info{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "INFO"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_log{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "LOG"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_notices_debug{instance=~\"${instance}:8001\"}[5m])",
       "legendFormat": "DEBUG"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful logins",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_sessions{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} "
      }
     ]
    },
    {
     "title": "Sessions Encryption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_postgres_ingress_postgres_sessions_encrypted{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - ENCRYPTED"
      },
      {
       "expr": "rate(envoy_postgres_ingress_postgres_sessions_unencrypted{instance=~\"${instance}:8001\"}[5m])*300",
       "legendFormat": "namespace: {{namespace}}, pod: {{pod}} - UNENCRYPTED"
      }
     ]
    }
   ]
  },
  {
   "title": "General Counters, Disks, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_static{instance=~\"${instance}:9187\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "stat",
     "description": "start time of the process",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"${instance}:9187\"} * 1000"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"${instance}:9187\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"${instance}:9187\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"${instance}:9187\"})"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "graph",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{instance=~\"${instance}:9187\"}[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"${instance}:9187\"}",
       "legendFormat": "Open FD"
      }
     ]
    },
    {
     "title": "Total / Available Disk Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"${instance}:9187\",fstype!=\"\"}",
       "legendFormat": "{{mountpoint}} Available"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=~\"${instance}:9187\",fstype!=\"\"}",
       "legendFormat": "{{mountpoint}} Total"
      }
     ]
    },
    {
     "title": "Total / Available Disk inodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"${instance}:9187\",fstype!=\"\"}",
       "legendFormat": "{{mountpoint}} inodes free"
      },
      {
       "expr": "node_filesystem_files{instance=~\"${instance}:9187\",fstype!=\"\"}",
       "legendFormat": "{{mountpoint}} inodes"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Role",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_replication_is_replica{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=~\"${instance}:9187\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_database_size{instance=~\"${instance}:9187\", datname!~\"template0|template1\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Database Disk Size",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 8 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Database Disk Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(1.0 - node_filesystem_avail_bytes{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"} / node_filesystem_size_bytes{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"}) * 100",
       "legendFormat": "Size"
      },
      {
       "expr": "(1.0 - node_filesystem_files_free{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"} / node_filesystem_files{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"}) * 100",
       "legendFormat": "inodes"
      }
     ]
    },
    {
     "title": "Database Disk inodes",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 12 },
     "targets": [
      {
       "expr": "node_filesystem_files{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_filesystem_files_free{instance=~\"${instance}:9187\",mountpoint~=\"/var/lib/postgresql|/var/db/postgresql\",fstype!=\"\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Top 10 bigger tables",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(topk(10, pg_total_relation_size_bytes{instance=~\"${instance}:9187\"}))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "More Consulted Tables (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (relname, instance,datname,schemaname) (rate(pg_stat_user_tables_idx_scan{instance=~\"${instance}:9187\"}[5m])) + sum by (relname, instance,datname,schemaname) (rate(pg_stat_user_tables_seq_scan{instance=~\"${instance}:9187\"}[5m])))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Table with more inserts (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_tup_ins{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Tables with more UPDATE operations (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_tup_upd{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Tables with more DELETE operations (Top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_tup_del{instance=~\"${instance}:9187\"}[5m]))",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index bloat Size (Top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_index_bloat_size{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schema_name}}, Table: {{tblname}}, Index: {{idxname}}"
      }
     ]
    },
    {
     "title": "Index Size (Top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_index_real_size{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schema_name}}, Table: {{tblname}}, Index: {{idxname}}"
      }
     ]
    },
    {
     "title": "Index Bloat Ratio (Top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, pg_index_bloat_ratio{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schema_name}}, Table: {{tblname}}, Index: {{idxname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dead tuples (top 10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_user_tables_n_dead_tup{instance=~\"${instance}:9187\"}[5m])*300)",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Table Bloat Ratio (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_table_bloat_bloat_ratio{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema:{{schemaname}}, Table: {{tablename}}"
      }
     ]
    },
    {
     "title": "Table Bloat Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_table_bloat_bloat_size{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{tablename}}"
      }
     ]
    },
    {
     "title": "Table pages Extra size (Top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, pg_table_bloat_extra_size{instance=~\"${instance}:9187\"})",
       "legendFormat": "Database: {{datname}}, Schema: {{schemaname}}, Table: {{tablename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Replica Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pg_replication_status_lag_size{instance=~\"${instance}:9187\", state=\"streaming\"} and on (instance)(pg_replication_is_replica == 0))"
      }
     ]
    },
    {
     "title": "Active Replication Slots",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(pg_replication_slots_stats_active{instance=~\"${instance}:9187\"}==1)"
      }
     ]
    },
    {
     "title": "Current LSN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_wal_position_bytes{instance=~\"${instance}:9187\"}"
      }
     ]
    },
    {
     "title": "Replication lag size",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_replication_status_lag_size{cluster_name=\"$cluster_name\"} and on (instance)(pg_replication_is_replica == 0)",
       "legendFormat": "Replica: {{application_name}}"
      }
     ]
    },
    {
     "title": "Replica with no streaming status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pg_replication_status_lag_size{instance=~\"${instance}:9187\", state!=\"streaming\"} and on (instance)(pg_replication_is_replica == 0))"
      }
     ]
    },
    {
     "title": "Inactive Replication Slots",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pg_replication_slots_stats_active{instance=~\"${instance}:9187\"}==0)"
      }
     ]
    },
    {
     "title": "Replication lag (seconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_replication_lag{cluster_name=\"$cluster_name\"} and on (instance)(pg_replication_is_replica == 1)",
       "legendFormat": "Replication lag in pod {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "No. WALs files archived",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_archiver_archived_count{instance=~\"${instance}:9187\"}[5m])*300",
       "legendFormat": "# of WALs archived"
      }
     ]
    },
    {
     "title": "Number of failed attempts for archiving WAL files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_archiver_failed_count{instance=~\"${instance}:9187\"}[5m])*300",
       "legendFormat": "# Archive attemps"
      }
     ]
    },
    {
     "title": "Last archive age (Seconds)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_stat_archiver_last_archive_age{instance=~\"${instance}:9187\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Queries Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_slow_queries{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Sequential Scans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20,rate(pg_stat_user_tables_seq_tup_read{instance=~\"${instance}:9187\"}[5m]))>0",
       "legendFormat": "Database: {{datname}}, Table: {{relname}}"
      }
     ]
    },
    {
     "title": "Long running transaction age(sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_long_running_transactions_age_in_seconds{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Blocked Queries Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_blocked_queries{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}, Table: {{table}}"
      }
     ]
    },
    {
     "title": "Number of long running transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_long_running_transactions_transactions{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Queries largest  time lock",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_oldest_blocked_age_seconds{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    },
    {
     "title": "Queries that are stuck being idle in transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stuck_idle_in_transaction_queries{instance=~\"${instance}:9187\"}",
       "legendFormat": "Database: {{datname}}"
      }
     ]
    }
   ]
  }
 ]
}