/*
 * Copyright (C) 2019 OnGres, Inc.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package io.stackgres.common;

import java.util.LinkedHashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * Base class that captures JSON properties this build does not model, so that a
 * deserialize/serialize round trip is lossless.
 *
 * <p>Without it, any read-modify-write of a custom resource rewrites the resource without the
 * fields the running build does not know about. That happens on every status update performed by
 * the cluster controller through
 * {@code AbstractCustomResourceWriter.update(T, java.util.function.Consumer)}, which replaces
 * the whole resource, and on every update performed through the REST API, which rebuilds the spec
 * from the DTO. After an operator upgrade the new CRD is installed and the new operator writes the
 * newly added fields while the pods still run the previous build of the cluster controller, so
 * without a catch-all those fields are silently dropped.</p>
 *
 * <p>The shape mirrors the generated fabric8 models (see
 * {@code io.fabric8.kubernetes.api.model.ObjectMeta}), with one deliberate difference: the
 * {@code Map} setter is null safe. Four details are load bearing:</p>
 *
 * <ul>
 *   <li>{@link JsonAnyGetter} together with {@link JsonIgnore} on {@link #getAdditionalProperties}.
 *   Since jackson-databind#4775 (2.19) an any-getter also registers as a regular getter, so without
 *   {@link JsonIgnore} the map would additionally be serialized under a literal
 *   {@code additionalProperties} key.</li>
 *   <li>{@link JsonIgnore} on the field, which keeps the map from being treated as a property of
 *   the models. It is also what {@code ModelTestUtil.getRepresentativeFields} looks at to leave the
 *   map out of the checks that walk the models reflectively.</li>
 *   <li>{@link #setAdditionalProperties(Map)}, which is the setter the builders generated by sundrio
 *   call from {@code build()}. It exists only for them and is not part of the JSON contract, hence
 *   the {@link JsonIgnore}.</li>
 *   <li>The null check in that setter. The models are built with {@code lazyMapInitEnabled = false},
 *   so the generated fluent holds a null map until something sets it, and {@code build()} passes
 *   that null along.</li>
 * </ul>
 *
 * <p>Models that declare their own {@code JsonIgnoreProperties} list still show
 * {@code additionalProperties} as a property of the OpenAPI schema published by the REST API, the
 * way the models extending a generated fabric8 model already did. It is only the published schema
 * that is affected, not what is serialized.</p>
 *
 * <p>The map is intentionally left out of {@code equals} and {@code hashCode} of the subclasses so
 * that comparing resources keeps ignoring properties this build does not model, as it did before.
 * </p>
 */
@RegisterForReflection
public abstract class AdditionalProperties {

  @JsonIgnore
  private Map<String, Object> additionalProperties = new LinkedHashMap<>();

  @JsonAnyGetter
  @JsonIgnore
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  @JsonAnySetter
  public void setAdditionalProperty(String name, Object value) {
    if (this.additionalProperties == null) {
      this.additionalProperties = new LinkedHashMap<>();
    }
    this.additionalProperties.put(name, value);
  }

  @JsonIgnore
  public void setAdditionalProperties(Map<String, Object> additionalProperties) {
    this.additionalProperties = additionalProperties == null
        ? new LinkedHashMap<>() : additionalProperties;
  }

}
