/*
 * Copyright (C) 2019 OnGres, Inc.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package io.stackgres.common;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Stream;

import io.stackgres.common.crd.CustomVolumeMount;
import io.stackgres.common.crd.sgcluster.StackGresCluster;
import io.stackgres.common.crd.sgcluster.StackGresClusterConfigurations;
import io.stackgres.common.crd.sgcluster.StackGresClusterConfigurationsPostgres;
import io.stackgres.common.crd.sgcluster.StackGresClusterPods;
import io.stackgres.common.crd.sgcluster.StackGresClusterPodsCustomPersistentVolume;
import io.stackgres.common.crd.sgcluster.StackGresClusterPodsPersistentVolume;
import io.stackgres.common.crd.sgcluster.StackGresClusterPodsPersistentVolumeIoLimits;
import io.stackgres.common.crd.sgcluster.StackGresClusterSpec;

/**
 * Utilities shared by the operator and the cluster controller to deal with
 * {@code SGCluster.spec.pods.customPersistentVolumes}.
 *
 * <p>Each custom persistent volume is generated as a StatefulSet volume claim template named
 * {@code custom-<name>} (see {@link StackGresVolume#CUSTOM}) so that users reference them in
 * {@code SGCluster.spec.pods.customVolumeMounts} exactly like custom volumes. Volumes that are
 * part of the coherent data set (or define I/O limits) are also mounted, at the root of the
 * PersistentVolumeClaim without any subPath, in the cluster controller container under
 * {@link ClusterPath#CUSTOM_PERSISTENT_VOLUMES_PATH}.</p>
 */
public interface CustomPersistentVolumeUtil {

  static List<StackGresClusterPodsCustomPersistentVolume> getCustomPersistentVolumes(
      StackGresCluster cluster) {
    return getCustomPersistentVolumes(Optional.ofNullable(cluster)
        .map(StackGresCluster::getSpec)
        .orElse(null));
  }

  static List<StackGresClusterPodsCustomPersistentVolume> getCustomPersistentVolumes(
      StackGresClusterSpec spec) {
    return getCustomPersistentVolumes(Optional.ofNullable(spec)
        .map(StackGresClusterSpec::getPods)
        .orElse(null));
  }

  static List<StackGresClusterPodsCustomPersistentVolume> getCustomPersistentVolumes(
      StackGresClusterPods pods) {
    return Optional.ofNullable(pods)
        .map(StackGresClusterPods::getCustomPersistentVolumes)
        .orElse(List.of());
  }

  static Optional<String> getWalPath(StackGresCluster cluster) {
    return getWalPath(Optional.ofNullable(cluster)
        .map(StackGresCluster::getSpec)
        .orElse(null));
  }

  static Optional<String> getWalPath(StackGresClusterSpec spec) {
    return Optional.ofNullable(spec)
        .map(StackGresClusterSpec::getConfigurations)
        .map(StackGresClusterConfigurations::getPostgres)
        .map(StackGresClusterConfigurationsPostgres::getWalPath);
  }

  static String volumeName(StackGresClusterPodsCustomPersistentVolume customPersistentVolume) {
    return volumeName(customPersistentVolume.getName());
  }

  static String volumeName(String name) {
    return StackGresVolume.CUSTOM.getName(name);
  }

  static Path controllerMountPath(
      StackGresClusterPodsCustomPersistentVolume customPersistentVolume) {
    return controllerMountPath(customPersistentVolume.getName());
  }

  static Path controllerMountPath(String name) {
    return Paths.get(ClusterPath.CUSTOM_PERSISTENT_VOLUMES_PATH.path()).resolve(name);
  }

  /**
   * Prefix of the name of the PersistentVolumeClaims generated by the StatefulSet for the
   * custom persistent volume with the given name (the StatefulSet controller appends the
   * {@code -<index>} suffix of the Pod name).
   */
  static String podPersistentVolumeClaimName(StackGresCluster cluster, String name) {
    return volumeName(name) + "-" + cluster.getMetadata().getName();
  }

  static boolean isCoherentData(
      StackGresClusterPodsCustomPersistentVolume customPersistentVolume) {
    return Boolean.TRUE.equals(customPersistentVolume.getCoherentData());
  }

  static boolean hasIoLimits(StackGresClusterPodsPersistentVolumeIoLimits ioLimits) {
    return ioLimits != null
        && (ioLimits.getReadIops() != null
            || ioLimits.getWriteIops() != null
            || ioLimits.getReadMiBps() != null
            || ioLimits.getWriteMiBps() != null);
  }

  /**
   * Return true when I/O limits are set for the data volume or any custom persistent volume.
   */
  static boolean hasAnyIoLimits(StackGresCluster cluster) {
    return Optional.ofNullable(cluster.getSpec())
        .map(StackGresClusterSpec::getPods)
        .map(StackGresClusterPods::getPersistentVolume)
        .map(StackGresClusterPodsPersistentVolume::getIoLimits)
        .filter(CustomPersistentVolumeUtil::hasIoLimits)
        .isPresent()
        || getCustomPersistentVolumes(cluster).stream()
            .map(StackGresClusterPodsCustomPersistentVolume::getIoLimits)
            .anyMatch(CustomPersistentVolumeUtil::hasIoLimits);
  }

  /**
   * Return the custom persistent volumes that must be mounted, at the root of the
   * PersistentVolumeClaim without any subPath, in the cluster controller container: those that
   * are part of the coherent data set (for the data coherence check) and those defining I/O
   * limits (to resolve the backing device from the mount).
   */
  static List<StackGresClusterPodsCustomPersistentVolume> getControllerMountedVolumes(
      StackGresCluster cluster) {
    return getCustomPersistentVolumes(cluster).stream()
        .filter(customPersistentVolume -> isCoherentData(customPersistentVolume)
            || hasIoLimits(customPersistentVolume.getIoLimits()))
        .toList();
  }

  static boolean isAllowCoherentDataRemoval(
      StackGresClusterPodsCustomPersistentVolume customPersistentVolume) {
    return Boolean.TRUE.equals(customPersistentVolume.getAllowCoherentDataRemoval());
  }

  /**
   * Return the mounts of the volume generated for the custom persistent volume with the given
   * name declared for the patroni container in
   * {@code SGCluster.spec.pods.customVolumeMounts}.
   */
  static List<CustomVolumeMount> patroniMountsOf(StackGresCluster cluster, String name) {
    return patroniMountsOf(Optional.ofNullable(cluster)
        .map(StackGresCluster::getSpec)
        .orElse(null), name);
  }

  static List<CustomVolumeMount> patroniMountsOf(StackGresClusterSpec spec, String name) {
    return patroniMountsOf(Optional.ofNullable(spec)
        .map(StackGresClusterSpec::getPods)
        .orElse(null), name);
  }

  static List<CustomVolumeMount> patroniMountsOf(StackGresClusterPods pods, String name) {
    final String volumeName = volumeName(name);
    return Optional.ofNullable(pods)
        .map(StackGresClusterPods::getCustomVolumeMounts)
        .map(customVolumeMounts -> customVolumeMounts
            .get(StackGresContainer.PATRONI.getName()))
        .stream()
        .flatMap(List::stream)
        .filter(mount -> volumeName.equals(mount.getName()))
        .toList();
  }

  /**
   * Return the directories, relative to the mount of each custom persistent volume at the root
   * of the PersistentVolumeClaim (see {@link #controllerMountPath(String)}), of every subPath
   * declared in {@code SGCluster.spec.pods.customVolumeMounts} and
   * {@code SGCluster.spec.pods.customInitVolumeMounts} for any container. Those directories
   * must be created before any container using the subPath is started since kubelet creates
   * missing subPath directories owned by root (making them unwritable for postgres).
   */
  static List<String> declaredSubPathDirectories(StackGresCluster cluster) {
    return getCustomPersistentVolumes(cluster).stream()
        .flatMap(customPersistentVolume -> Stream.concat(
            Optional.ofNullable(cluster.getSpec())
                .map(StackGresClusterSpec::getPods)
                .map(StackGresClusterPods::getCustomVolumeMounts)
                .stream()
                .flatMap(customVolumeMounts -> customVolumeMounts.values().stream())
                .flatMap(List::stream),
            Optional.ofNullable(cluster.getSpec())
                .map(StackGresClusterSpec::getPods)
                .map(StackGresClusterPods::getCustomInitVolumeMounts)
                .stream()
                .flatMap(customVolumeMounts -> customVolumeMounts.values().stream())
                .flatMap(List::stream))
            .filter(mount -> volumeName(customPersistentVolume).equals(mount.getName()))
            .map(CustomVolumeMount::getSubPath)
            .filter(Objects::nonNull)
            .filter(subPath -> !subPath.isEmpty())
            .map(subPath -> controllerMountPath(customPersistentVolume)
                .resolve(subPath).toString()))
        .distinct()
        .toList();
  }

  /**
   * Translate an absolute path as seen by the patroni container to the equivalent path as seen
   * by the cluster controller container.
   *
   * <p>Paths under the data volume ({@link ClusterPath#PG_BASE_PATH}) are returned unchanged
   * since the data volume is mounted at the same path in both containers. Paths under a mount
   * of a custom persistent volume are translated to the corresponding path under the mount of
   * the PersistentVolumeClaim root in the cluster controller container, taking the mount
   * subPath into account. Returns empty when the path can not be translated (it does not
   * belong to the data volume nor to any custom persistent volume mount of the patroni
   * container).</p>
   */
  static Optional<Path> translatePatroniPathToController(
      StackGresCluster cluster, String patroniPath) {
    final Path path = Paths.get(patroniPath).normalize();
    if (path.startsWith(Paths.get(ClusterPath.PG_BASE_PATH.path()))) {
      return Optional.of(path);
    }
    return getCustomPersistentVolumes(cluster)
        .stream()
        .flatMap(customPersistentVolume -> patroniMountsOf(
            cluster, customPersistentVolume.getName())
            .stream()
            .map(mount -> Map.entry(customPersistentVolume, mount)))
        .filter(volumeAndMount -> path.startsWith(
            Paths.get(volumeAndMount.getValue().getMountPath())))
        .findFirst()
        .map(volumeAndMount -> {
          final Path mountPath = Paths.get(volumeAndMount.getValue().getMountPath());
          final Path volumeRoot = controllerMountPath(volumeAndMount.getKey());
          final Path subPathRelativePath = Optional
              .ofNullable(volumeAndMount.getValue().getSubPath())
              .map(volumeRoot::resolve)
              .orElse(volumeRoot);
          return subPathRelativePath.resolve(mountPath.relativize(path));
        });
  }

}
