#!/bin/sh

check_pod_annotation(){
  local INSTANCE="$1"
  local EXPECTED_ANNOTATION_VALUE="$2"

  local POD_ANNOTATION=${POD_ANNOTATION:-"test-annotation"}

  local ACTUAL_ANNOTATION=$(kubectl get pod -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-"$INSTANCE" -o jsonpath="{.metadata.annotations.$POD_ANNOTATION}")

  if assert_string_equal "$EXPECTED_ANNOTATION_VALUE" "$ACTUAL_ANNOTATION"
  then 
    echo "SUCCESS. Custom annotations were created"
  else
    echo "FAIL. Custom annotations did not match the expected value"
    return 1
  fi
}


check_service_annotation(){
  local INSTANCE="$1"
  local EXPECTED_ANNOTATION_VALUE="$2"
  local SERVICE_ANNOTATION=${SERVICE_ANNOTATION:-"service-annotation"}

  local ACTUAL_ANNOTATION=$(kubectl get service -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-"$INSTANCE" -o jsonpath="{.metadata.annotations.$SERVICE_ANNOTATION}")

  if assert_string_equal "$EXPECTED_ANNOTATION_VALUE" "$ACTUAL_ANNOTATION"
  then 
    echo "SUCCESS. Custom annotations were created"
  else
    echo "FAIL. Custom annotations did not match the expected value"
    return 1
  fi
}