#!/bin/sh

check_connectivity(){

  check_service_connectivity

  RESPONSE_5434="$(run_query -p 5434 $@)"
  RESPONSE_5435="$(run_query -p 5435 $@)"
  
  if [ "$RESPONSE_5434" = "1" ] && [ "$RESPONSE_5435" = "1" ]
  then
    return 0
  else 
    return 1
  fi

}

check_service_connectivity(){

  RESPONSE_5432="$(run_query -p 5432 $@)"
  RESPONSE_5433="$(run_query -p 5433 $@)"
  
  if [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_5433" = "1" ]
  then
    return 0
  else 
    return 1
  fi

}