#!/bin/sh

event_watch() {
  local NAMESPACE="--all-namespaces"
  local OUTPUT=wide
  while [ "$#" -gt 0 ]
  do
    case "$1" in
      -n|--namespace)
        shift
        NAMESPACE="--namespace $1"
        shift
        ;;
      -o)
        shift
        OUTPUT="$1"
        shift
        ;;
      *)
        echo >&2 "Unknown parameter $1 (use: --namespace <namespace>;)"
        return 1
        ;;
    esac
  done
  trap_exec kubectl get event "$NAMESPACE" --watch-only --no-headers -o json \
    | jq --unbuffered -r '.metadata.namespace + "/" + .metadata.name' \
    | xargs_shell % -ec "kubectl get event -o '$OUTPUT' --no-headers -n \"\$(echo '%' | cut -d '/' -f 1)\" \"\$(echo '%' | cut -d '/' -f 2)\" 2>/dev/null || true" \
    | (
      set +x
      while IFS="$(printf '\n')" read EVENT
      do
        echo_raw "$(date --iso-8601=seconds) $EVENT"
      done
      )
}
