#!/bin/sh

event_watch() {
  local namespace
  local output=wide
  while [ "$#" -gt 0 ]
  do
    case "$1" in
      -n|--namespace)
        shift
        namespace="$1"
        shift
        ;;
      -o)
        shift
        output="$1"
        shift
        ;;
      *)
        echo >&2 "Unknown parameter $1 (use: --namespace <namespace>;)"
        return 1
        ;;
    esac
  done
  trap_exec kubectl get event $(if [ -z "$namespace" ]; then echo '--all-namespaces'; else echo '-n '"$namespace"; fi) --watch-only --no-headers -o json \
    | jq --unbuffered -r '.metadata.namespace + "/" + .metadata.name' \
    | xargs -r -n 1 -I % "$SHELL" $SHELL_XTRACE -ec 'kubectl get event -o '"'$output'"' --no-headers -n "$(echo "%" | cut -d "/" -f 1)" "$(echo "%" | cut -d "/" -f 2)" 2>/dev/null || true' \
    | xargs -r -n 1 -I % "$SHELL" $SHELL_XTRACE -ec "echo \"$(date --iso-8601=seconds)\"' %'"
}
