#!/bin/sh

operator_to_yaml() {
  export CREATE_NS=true
  helm_to_yaml "$OPERATOR_CHART_PATH" "$@"
}

cluster_to_yaml() {
  export CREATE_NS=false
  helm_to_yaml "$CLUSTER_CHART_PATH" "$@"
}

#
helm_to_yaml() {
  local NAMESPACE="${NAMESPACE:-default}" # FIXME! this should be a global e2e namespace as a default and export
  local CHART="$1"
  shift
  
  if [ -z "$CHART" ]
  then
    >&2 echo "Chart $CHART is not defined"
    exit 1
  fi

  (
  if $CREATE_NS
  then
    cat << EOF
---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
EOF
  true
  fi
  helm template --namespace "$NAMESPACE" "$@" "$CHART" | ($CREATE_NS && cat || grep -v "^  namespace: \"$NAMESPACE\"$")

  )
}

test_chart() {
  helm install --namespace "$NAMESPACE" "$@" "$CHART" | ($CREATE_NS && cat || grep -v "^  namespace: \"$NAMESPACE\"$")
}