#!/bin/sh

export E2E_ENV="${E2E_ENV:-kind}"
export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
export DEFAULT_K8S_VERSION="1.13.12"
export K8S_VERSION="${K8S_VERSION:-$DEFAULT_K8S_VERSION}"

. "$(dirname "$0")/envs/$E2E_ENV"

setup_k8s() {
  mkdir -p "$TARGET_PATH/logs"

  if [ "$E2E_SKIP_SETUP" = true ]
  then
    return
  fi

  if [ "$K8S_REUSE" != true ]
  then
    reset_k8s
  else
    reuse_k8s
  fi
}

create_namespace_if_not_exists(){
  if ! kubectl get namespace "$1" > /dev/null
  then
    kubectl create namespace "$1"
  fi
}

delete_namespace_if_exists() {
  local NAMESPACE="$1"

  if kubectl get namespaces $NAMESPACE  > /dev/null 2>&1
  then
    kubectl delete namespace $NAMESPACE
  fi
}
