#!/bin/sh

listen_job() {
  PODID="$(kubectl get pods --all-namespaces | grep stackgres-operator-init | grep '\w\+-\w\+-\w\+-\(\w\+\)' -o)"
  STACKGRES_NAMESPACE="$(kubectl get pods --all-namespaces | grep stackgres-operator-init | cut -d ' ' -f 1)"
  kubectl logs -f "$PODID" -n "$STACKGRES_NAMESPACE"
}