#!/bin/sh

listen_operator_logs() {
  PODID="$(kubectl get pods --all-namespaces | grep stackgres-operator | grep -v stackgres-operator-init | grep '\w\+-\w\+-\w\+-\(\w\+\)' -o)"
  STACKGRES_NAMESPACE="$(kubectl get pods --all-namespaces | grep stackgres-operator | grep -v stackgres-operator-init | cut -d ' ' -f 1)"
  clear
  kubectl logs -f "$PODID" -n "$STACKGRES_NAMESPACE" stackgres-operator
}

listen_operator() {
  until listen_operator_logs
  do
    sleep 2
  done
}