#!/bin/sh

setup_logs() {
  if [ "$E2E_DISABLE_LOGS" = "true" ]
  then
    return
  fi
  echo "Recording resources"
  resource_watch --log-in-files > "$TARGET_PATH/all_resources.log" 2>/dev/null &
  trap_kill "$!"
  echo "Recording pods logs"
  pod_logs --log-in-files > "$TARGET_PATH/all_pods.log" 2>/dev/null &
  trap_kill "$!"
  echo "Recording events"
  event_watch -o wide > "$TARGET_PATH/all_events.log" 2>/dev/null &
  trap_kill "$!"
}
