#!/bin/sh
# shellcheck disable=SC2018

random_string(){
  printf "%s" "$(tr -dc 'a-zA-Z' </dev/urandom | head -c 1)$(tr -dc 'a-zA-Z0-9' </dev/urandom | head -c "${1:-31}")"
}

random_string_lowercase(){
  printf "%s" "$(tr -dc 'a-z' </dev/urandom | head -c 1)$(tr -dc 'a-z0-9' </dev/urandom | head -c "${1:-31}")"
}