#!/bin/sh

run_query() {
  local CLUSTER_NAME="$CLUSTER_NAME"
  local INSTANCE=0
  local CLUSTER_NAMESPACE="$CLUSTER_NAMESPACE"
  local QUERY="'SELECT 1'"
  local PORT=5432
  local HOST=127.0.0.1
  local DATABASE=postgres
  
  while getopts ":c:n:i:q:p:h:d:" opt; do
    case $opt in
      c) CLUSTER_NAME="$OPTARG"
      ;;
      n) CLUSTER_NAMESPACE="$OPTARG"
      ;;
      i) INSTANCE="$OPTARG"
      ;;
      q) QUERY="$OPTARG"
      ;;
      p) PORT="$OPTARG"
      ;;
      h) HOST="$OPTARG"
      ;;
      d) DATABASE="$OPTARG"
      ;;
      \?) echo "Invalid option -$OPTARG" >&2
      ;;
    esac
  done
  
  kubectl exec -t -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME-$INSTANCE" -c postgres-util -- sh -c "PGPASSWORD=$(kubectl -n "$CLUSTER_NAMESPACE" get secrets "$CLUSTER_NAME" -o jsonpath='{.data.superuser-password}' | base64 -d) PGCONNECT_TIMEOUT=5 psql -t -A -U postgres -d $DATABASE -p $PORT -c $QUERY -h $HOST"
}