#!/bin/sh

setup_tiller() {

  if ! kubectl get pods --all-namespaces  | grep tiller | grep Running | grep 1/1; then
    helm init

    helm repo update

    wait_tiller_is_loaded

    kubectl get serviceaccount --namespace kube-system tiller | grep -q '^tiller\s' \
      || kubectl create serviceaccount --namespace kube-system tiller
    kubectl get clusterrolebinding tiller-cluster-rule | grep -q '^tiller-cluster-rule\s' \
      || kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
    kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
  else 
    echo "Tiller already loaded"
  fi 
}

is_tiller_loaded(){
  if kubectl get pods --all-namespaces  | grep tiller | grep Running | grep 1/1; then
    return 0
  else
    return 1
  fi
}

wait_tiller_is_loaded() {
  while true
  do

    if kubectl get pods --all-namespaces  | grep tiller | grep Running | grep 1/1; then
      echo "Tiller loaded"
      break
    fi

    sleep 2

  done
}