#!/bin/sh

setup_default_limits() {
  cat << EOF | kubectl apply -f -
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      cpu: $1
    defaultRequest:
      cpu: $2
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: $3
    defaultRequest:
      memory: $4
    type: Container
EOF
}