#!/bin/sh

e2e_test_before_all() {
  true
}

e2e_test_install() {
  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "$(e2e_test_install_pods)"

  wait_pods_running "$CLUSTER_NAMESPACE" "$(e2e_test_install_pods)"
}

e2e_test_install_pods() {
  echo 1
}

e2e_test() {
  echo "You should define a test function"
  false
}

e2e_test_uninstall() {
  helm_cleanup_chart "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"

  k8s_async_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test_after_all() {
  true
}

e2e_exclusive_lock() {
  false
}

spec() {
  local RESULT
  local EXIT_CODE
  local SPEC_FILE="$1"
  local SPEC_BEFORE_FILE="$SPEC_FILE.before"
  local SPEC_AFTER_FILE="$SPEC_FILE.after"
  local SPEC_VALUES_FILE="$1.values.yaml"
  local SPEC_PATH="$(dirname "$SPEC_FILE")"
  local SPEC_NAME="$(basename "$SPEC_FILE")"
  local CLUSTER_NAMESPACE="$SPEC_NAME-$(printf '%x' "$(date +%s)")"
  local CLUSTER_NAME="$SPEC_NAME"
  local E2E_SKIP_SPEC_INSTALL="${E2E_SKIP_SPEC_INSTALL:-false}"
  local E2E_SKIP_SPEC_BEFORE_ALL="${E2E_SKIP_SPEC_BEFORE_ALL:-false}"
  local E2E_SKIP_SPEC_AFTER_ALL="${E2E_SKIP_SPEC_AFTER_ALL:-false}"
  local LOG_PATH="$TARGET_PATH/logs/$SPEC_NAME"
  export SPEC_FILE SPEC_NAME CLUSTER_NAMESPACE CLUSTER_NAME LOG_PATH

  mkdir -p "$LOG_PATH"

  if [ ! -f "$SPEC_VALUES_FILE" ]
  then
    SPEC_VALUES_FILE="$SPEC_PATH/default.values.yaml"
  fi

  . "$SPEC_FILE"

  if "${E2E_LOCK:-true}" && e2e_exclusive_lock
  then
    E2E_LOCK=false flock "$TARGET_PATH/exclusive-lock" \
      "$SHELL" $SHELL_XTRACE "$(dirname "$0")/e2e" spec "$1"
    return
  fi

  if "${E2E_LOCK:-true}"
  then
    E2E_LOCK=false flock -s "$TARGET_PATH/exclusive-lock" \
      "$SHELL" $SHELL_XTRACE "$(dirname "$0")/e2e" spec "$1"
    return
  fi

  flock "$TARGET_PATH/check-operator-lock" \
      "$SHELL" $SH_OPTS "$(dirname "$0")/e2e" reinstall_operator_if_not_as_expected

  rm -f "$TARGET_PATH/$SPEC_NAME.failed"

  echo
  echo "================================================================"
  echo "Running $SPEC_NAME tests"
  echo "================================================================"
  echo

  local START="$(date +%s)"
  echo -n > "$LOG_PATH/$SPEC_NAME.log"
  (
    set +ex
    "$SHELL" +x -c 'echo $$; exec tail -f '"$LOG_PATH/$SPEC_NAME.log" \
      | (
      read pid
      trap_kill "$pid"
      while IFS="\n" read -r line
      do
        echo_raw "$(date +"%Y-%m-%d %H:%M:%S") [$SPEC_NAME] $line"
      done
      )
  ) &
  try_function run_spec >> "$LOG_PATH/$SPEC_NAME.log" 2>&1
  if ! "$RESULT"
  then
    echo "$SPEC_NAME. FAIL. See file $LOG_PATH/$SPEC_NAME.log for details" > "$TARGET_PATH/$SPEC_NAME.failed"
    echo "$SPEC_NAME. FAIL. See file $LOG_PATH/$SPEC_NAME.log for details" >> "$TARGET_PATH/logs/results.log"
    if [ "$E2E_SPEC_TRY_UNINSTALL_ON_FAILURE" = "true" ]
    then
      cleanup_spec || true
    fi
    return "$EXIT_CODE"
  fi
  echo "$SPEC_NAME. SUCCESS. Test took $(($(date +%s)-START)) seconds" >> "$TARGET_PATH/logs"/results.log
}

run_spec() {
  if [ "$E2E_SKIP_SPEC_BEFORE_ALL" != true ]
  then
    e2e_test_before_all
  fi

  if [ "$E2E_SKIP_SPEC_INSTALL" != true ]
  then
    e2e_test_install
  fi

  e2e_test

  cleanup_spec
}

cleanup_spec(){

  if [ "$E2E_SKIP_SPEC_UNINSTALL" != true ]
  then
    e2e_test_uninstall
  fi

  e2e_test_after_all

}
