#!/bin/sh

export E2E_TIMEOUT="${E2E_TIMEOUT:-180}"

wait_until() {
  notrace_function traceable_wait_until "$@"
}

traceable_wait_until() {
  local RESULT
  local EXIT_CODE
  local START="$(date +%s)"
  local TIMEOUT="$E2E_TIMEOUT"
  local INTERVAL=2
  local OUTPUT_PATH="$LOG_PATH/wait-until-$START-$(shuf -i 0-65535 -n 1).log"
  while echo_raw "$1" | grep -q '^-'
  do
    if [ "$1" = "-t" ]
    then
      shift
      TIMEOUT="$1"
      shift
    fi
    if [ "$1" = "-i" ]
    then
      shift
      INTERVAL="$1"
      shift
    fi
  done
  echo -n >"$OUTPUT_PATH"
  while [ "$((START + TIMEOUT))" -gt "$(date +%s)" ]
  do
    try_function "$@" >>"$OUTPUT_PATH" 2>&1
    if "$RESULT"
    then
      return
    fi
    sleep "$INTERVAL"
  done
  cat "$OUTPUT_PATH"
  return 1
}
