#!/bin/sh

wait_until() {
  local RESULT
  local EXIT_CODE
  local START="$(date +%s)"
  local TIMEOUT="$E2E_TIMEOUT"
  local OUTPUT_PATH="$LOG_PATH/wait-until-$START-$(shuf -i 0-65535 -n 1).log"
  if [ "$1" = "-t" ]
  then
    shift
    TIMEOUT="$1"
    shift
  fi
  echo -n >"$OUTPUT_PATH"
  while [ "$((START + TIMEOUT))" -gt "$(date +%s)" ]
  do
    try_function "$@" >>"$OUTPUT_PATH" 2>&1
    if "$RESULT"
    then
      return
    fi
    sleep 2
  done
  cat "$OUTPUT_PATH"
  return 1
}