#!/bin/sh

wait_certificate_approval() {
  if kubectl wait --timeout="$E2E_TIMEOUT"s csr stackgres-operator --for=condition=Approved
  then
    echo "Certificate approved"
  else
    echo "Timeout while waiting for certificate approval"
    return 1
  fi
}
