#!/bin/sh

e2e_test_install() {
  NODE_LABEL_KEY="$(random_string)"
  NODE_LABEL_VALUE="$(random_string)"

  kubectl create namespace "$CLUSTER_NAMESPACE"

  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 1 \
    --set-string "cluster.pods.scheduling.nodeSelector.$NODE_LABEL_KEY=$NODE_LABEL_VALUE" \
    --set-string "distributedLogs.scheduling.nodeSelector.$NODE_LABEL_KEY=$NODE_LABEL_VALUE"
}

e2e_test_uninstall() {
  helm_cleanup_chart "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"

  k8s_async_cleanup_namespace "$CLUSTER_NAMESPACE"
}

e2e_test() {
  run_test "sgcluster has specified node selector" check_sgcluster_has_node_selector

  run_test "sgcluster's StatefulSet has specified node selector" check_sgcluster_sts_has_node_selector

  # Skip distributedlogs test since it is not possible to create with previous version.
}

check_sgcluster_has_node_selector() {
  if [ "$(kubectl get sgcluster -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" \
    --template "{{ (index .spec.pods.scheduling.nodeSelector \"$NODE_LABEL_KEY\") }}")" \
    = "$NODE_LABEL_VALUE" ]
  then
    success "sgcluster has the configured node selector"
  else
    fail "sgcluster has not the configured node selector"
  fi
}

check_sgcluster_sts_has_node_selector() {
  echo "Waiting for sts with node selector"  
  try_function wait_until eval "$(cat << 'EOF'
[ "$(kubectl get sts -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" \
  --template "{{ (index .spec.template.spec.nodeSelector \"$NODE_LABEL_KEY\") }}")" \
  = "$NODE_LABEL_VALUE" ]
EOF
    )"
  if "$RESULT"
  then
    success "sgcluster's StatefulSet has the configured node selector"
  else
    fail "sgcluster's StatefulSet has not the configured node selector"
  fi
}
