/*
 * Copyright (C) 2019 OnGres, Inc.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package io.stackgres.common;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Map;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.fabric8.kubernetes.client.utils.KubernetesSerialization;
import io.stackgres.common.crd.SecretKeySelector;
import io.stackgres.common.crd.sgcluster.StackGresCluster;
import io.stackgres.common.crd.sgcluster.StackGresClusterPods;
import io.stackgres.common.crd.sgcluster.StackGresClusterPodsBuilder;
import io.stackgres.common.crd.sgcluster.StackGresClusterSpec;
import org.junit.jupiter.api.Test;

class AdditionalPropertiesTest {

  private static ObjectMapper customizedMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    new JsonMapperCustomizer().customize(objectMapper);
    return objectMapper;
  }

  /**
   * The mapper used by the Kubernetes client does not disable FAIL_ON_UNKNOWN_PROPERTIES, so the
   * catch-all has to work without it too.
   */
  private static ObjectMapper strictMapper() {
    return new ObjectMapper()
        .enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
  }

  @Test
  void unknownPropertyIsCapturedAndSerializedBack() throws Exception {
    for (ObjectMapper objectMapper : new ObjectMapper[] {customizedMapper(), strictMapper()}) {
      StackGresClusterPods pods = objectMapper.readValue(
          """
          {"disableEnvoy":true,"futureField":{"anInteger":1,"aList":["a","b"]}}
          """,
          StackGresClusterPods.class);

      assertEquals(true, pods.getDisableEnvoy());
      assertTrue(pods.getAdditionalProperties().containsKey("futureField"));

      JsonNode json = objectMapper.valueToTree(pods);
      assertTrue(json.has("futureField"));
      assertEquals(1, json.get("futureField").get("anInteger").asInt());
      assertEquals("b", json.get("futureField").get("aList").get(1).asText());
    }
  }

  /**
   * Since jackson-databind#4775 an any-getter is also collected as a regular getter, so without
   * {@code @JsonIgnore} on {@code getAdditionalProperties()} the map would be serialized a second
   * time under a literal {@code additionalProperties} key.
   */
  @Test
  void additionalPropertiesIsNotSerializedAsAProperty() {
    StackGresClusterPods pods = new StackGresClusterPods();
    pods.setAdditionalProperty("futureField", "aValue");

    JsonNode json = customizedMapper().valueToTree(pods);

    assertTrue(json.has("futureField"));
    assertFalse(json.has("additionalProperties"),
        "the map must be flattened, not serialized under its own name");
  }

  /**
   * A property literally named {@code additionalProperties} is captured by the any-setter like any
   * other unknown property, and is therefore written back unchanged. It is nested one level inside
   * the map, which is an implementation detail, but the round trip is faithful and that is what
   * matters here.
   */
  @Test
  void propertyNamedAdditionalPropertiesRoundTrips() throws Exception {
    ObjectMapper objectMapper = customizedMapper();
    String json = "{\"additionalProperties\":{\"aKey\":\"aValue\"}}";

    StackGresClusterPods pods = objectMapper.readValue(json, StackGresClusterPods.class);

    assertEquals(objectMapper.readTree(json), objectMapper.valueToTree(pods));
  }

  /**
   * Properties named in {@code @JsonIgnoreProperties(value = ...)} are dropped before the
   * any-setter is consulted, so the deliberate exclusions keep working.
   */
  @Test
  void explicitlyIgnoredPropertiesAreNotCaptured() throws Exception {
    SecretKeySelector selector = customizedMapper().readValue(
        "{\"name\":\"aSecret\",\"key\":\"aKey\",\"optional\":true}", SecretKeySelector.class);

    assertEquals("aSecret", selector.getName());
    assertFalse(selector.getAdditionalProperties().containsKey("optional"));
  }

  /**
   * The builders generated by sundrio always call {@code setAdditionalProperties}, and with
   * {@code lazyMapInitEnabled = false} the value passed is null unless something set it.
   */
  @Test
  void builtObjectsAcceptAdditionalProperties() {
    StackGresClusterPods pods = new StackGresClusterPodsBuilder().build();

    assertDoesNotThrow(() -> pods.setAdditionalProperty("futureField", "aValue"));
    assertEquals("aValue", pods.getAdditionalProperties().get("futureField"));
  }

  @Test
  void builtObjectsKeepAdditionalPropertiesOfTheObjectTheyAreBuiltFrom() {
    StackGresClusterPods pods = new StackGresClusterPods();
    pods.setAdditionalProperty("futureField", "aValue");

    StackGresClusterPods copy = new StackGresClusterPodsBuilder(pods).build();

    assertEquals("aValue", copy.getAdditionalProperties().get("futureField"));
  }

  /**
   * The Kubernetes client serializes with its own mapper, which unlike the one the application
   * configures does not disable FAIL_ON_UNKNOWN_PROPERTIES. This is the round trip a read modify
   * write of a custom resource actually goes through.
   */
  @Test
  void unknownPropertiesSurviveTheKubernetesClientSerializer() {
    KubernetesSerialization serialization = new KubernetesSerialization();
    StackGresCluster cluster = new StackGresCluster();
    cluster.setSpec(new StackGresClusterSpec());
    cluster.getSpec().setAdditionalProperty("futureField", Map.of("aKey", "aValue"));

    String json = serialization.asJson(cluster);
    StackGresCluster copy = serialization.unmarshal(json, StackGresCluster.class);

    assertEquals(Map.of("aKey", "aValue"),
        copy.getSpec().getAdditionalProperties().get("futureField"));
  }

}
